//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crafting ähnelt.
        /// </summary>
        internal static string ABLCAT_CRAFTING {
            get {
                return ResourceManager.GetString("ABLCAT_CRAFTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defense ähnelt.
        /// </summary>
        internal static string ABLCAT_DEFENSE {
            get {
                return ResourceManager.GetString("ABLCAT_DEFENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offense ähnelt.
        /// </summary>
        internal static string ABLCAT_OFFENSE {
            get {
                return ResourceManager.GetString("ABLCAT_OFFENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighting Style ähnelt.
        /// </summary>
        internal static string ABLCAT_STYLE {
            get {
                return ResourceManager.GetString("ABLCAT_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL01 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl01 {
            get {
                return ResourceManager.GetString("Achievement_Lvl01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL02 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl02 {
            get {
                return ResourceManager.GetString("Achievement_Lvl02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL03 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl03 {
            get {
                return ResourceManager.GetString("Achievement_Lvl03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL04 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl04 {
            get {
                return ResourceManager.GetString("Achievement_Lvl04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL05 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl05 {
            get {
                return ResourceManager.GetString("Achievement_Lvl05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL06 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl06 {
            get {
                return ResourceManager.GetString("Achievement_Lvl06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL07 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl07 {
            get {
                return ResourceManager.GetString("Achievement_Lvl07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL08 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl08 {
            get {
                return ResourceManager.GetString("Achievement_Lvl08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LVL09 ähnelt.
        /// </summary>
        internal static string Achievement_Lvl09 {
            get {
                return ResourceManager.GetString("Achievement_Lvl09", resourceCulture);
            }
        }
    }
}
