//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.Items", typeof(Items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axe ähnelt.
        /// </summary>
        internal static string Family_Axe {
            get {
                return ResourceManager.GetString("Family_Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blunt Weapon ähnelt.
        /// </summary>
        internal static string Family_Blunt {
            get {
                return ResourceManager.GetString("Family_Blunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dagger ähnelt.
        /// </summary>
        internal static string Family_Dagger {
            get {
                return ResourceManager.GetString("Family_Dagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Boots ähnelt.
        /// </summary>
        internal static string Family_HeavyBoots {
            get {
                return ResourceManager.GetString("Family_HeavyBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Body Armor ähnelt.
        /// </summary>
        internal static string Family_HeavyChest {
            get {
                return ResourceManager.GetString("Family_HeavyChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Gloves ähnelt.
        /// </summary>
        internal static string Family_HeavyGloves {
            get {
                return ResourceManager.GetString("Family_HeavyGloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Helmet ähnelt.
        /// </summary>
        internal static string Family_HeavyHelmet {
            get {
                return ResourceManager.GetString("Family_HeavyHelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Shield ähnelt.
        /// </summary>
        internal static string Family_HeavyShield {
            get {
                return ResourceManager.GetString("Family_HeavyShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Boots ähnelt.
        /// </summary>
        internal static string Family_LightBoots {
            get {
                return ResourceManager.GetString("Family_LightBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Body Armor ähnelt.
        /// </summary>
        internal static string Family_LightChest {
            get {
                return ResourceManager.GetString("Family_LightChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Gloves ähnelt.
        /// </summary>
        internal static string Family_LightGloves {
            get {
                return ResourceManager.GetString("Family_LightGloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Helmet ähnelt.
        /// </summary>
        internal static string Family_LightHelmet {
            get {
                return ResourceManager.GetString("Family_LightHelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Shield ähnelt.
        /// </summary>
        internal static string Family_LightShield {
            get {
                return ResourceManager.GetString("Family_LightShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Blade ähnelt.
        /// </summary>
        internal static string Family_LongBlade {
            get {
                return ResourceManager.GetString("Family_LongBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Sword ähnelt.
        /// </summary>
        internal static string Family_LongSword {
            get {
                return ResourceManager.GetString("Family_LongSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One-Handed Axe ähnelt.
        /// </summary>
        internal static string Family_OneHandAxe {
            get {
                return ResourceManager.GetString("Family_OneHandAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One-Handed Mace ähnelt.
        /// </summary>
        internal static string Family_OneHandMace {
            get {
                return ResourceManager.GetString("Family_OneHandMace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polearm ähnelt.
        /// </summary>
        internal static string Family_Polearm {
            get {
                return ResourceManager.GetString("Family_Polearm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Blade ähnelt.
        /// </summary>
        internal static string Family_ShortBlade {
            get {
                return ResourceManager.GetString("Family_ShortBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Sword ähnelt.
        /// </summary>
        internal static string Family_ShortSword {
            get {
                return ResourceManager.GetString("Family_ShortSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spear ähnelt.
        /// </summary>
        internal static string Family_Spear {
            get {
                return ResourceManager.GetString("Family_Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed Axe ähnelt.
        /// </summary>
        internal static string Family_TwoHandAxe {
            get {
                return ResourceManager.GetString("Family_TwoHandAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed Mace ähnelt.
        /// </summary>
        internal static string Family_TwoHandMace {
            get {
                return ResourceManager.GetString("Family_TwoHandMace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed Sword ähnelt.
        /// </summary>
        internal static string Family_TwoHandSword {
            get {
                return ResourceManager.GetString("Family_TwoHandSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knife ähnelt.
        /// </summary>
        internal static string Genus_Dagger0 {
            get {
                return ResourceManager.GetString("Genus_Dagger0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dagger ähnelt.
        /// </summary>
        internal static string Genus_Dagger1 {
            get {
                return ResourceManager.GetString("Genus_Dagger1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_Dagger2 {
            get {
                return ResourceManager.GetString("Genus_Dagger2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_HeavyBoots0 {
            get {
                return ResourceManager.GetString("Genus_HeavyBoots0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chain Boots ähnelt.
        /// </summary>
        internal static string Genus_HeavyBoots1 {
            get {
                return ResourceManager.GetString("Genus_HeavyBoots1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greaves ähnelt.
        /// </summary>
        internal static string Genus_HeavyBoots2 {
            get {
                return ResourceManager.GetString("Genus_HeavyBoots2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Armor ähnelt.
        /// </summary>
        internal static string Genus_HeavyChest0 {
            get {
                return ResourceManager.GetString("Genus_HeavyChest0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chain Mail ähnelt.
        /// </summary>
        internal static string Genus_HeavyChest1 {
            get {
                return ResourceManager.GetString("Genus_HeavyChest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breast Plate ähnelt.
        /// </summary>
        internal static string Genus_HeavyChest2 {
            get {
                return ResourceManager.GetString("Genus_HeavyChest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_HeavyGloves0 {
            get {
                return ResourceManager.GetString("Genus_HeavyGloves0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chain Gloves ähnelt.
        /// </summary>
        internal static string Genus_HeavyGloves1 {
            get {
                return ResourceManager.GetString("Genus_HeavyGloves1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gauntlets ähnelt.
        /// </summary>
        internal static string Genus_HeavyGloves2 {
            get {
                return ResourceManager.GetString("Genus_HeavyGloves2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_HeavyHelmet0 {
            get {
                return ResourceManager.GetString("Genus_HeavyHelmet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helmet ähnelt.
        /// </summary>
        internal static string Genus_HeavyHelmet1 {
            get {
                return ResourceManager.GetString("Genus_HeavyHelmet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full Helmet ähnelt.
        /// </summary>
        internal static string Genus_HeavyHelmet2 {
            get {
                return ResourceManager.GetString("Genus_HeavyHelmet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Shield ähnelt.
        /// </summary>
        internal static string Genus_HeavyShield0 {
            get {
                return ResourceManager.GetString("Genus_HeavyShield0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kite Shield ähnelt.
        /// </summary>
        internal static string Genus_HeavyShield1 {
            get {
                return ResourceManager.GetString("Genus_HeavyShield1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tower Shield ähnelt.
        /// </summary>
        internal static string Genus_HeavyShield2 {
            get {
                return ResourceManager.GetString("Genus_HeavyShield2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_LightBoots0 {
            get {
                return ResourceManager.GetString("Genus_LightBoots0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shoes ähnelt.
        /// </summary>
        internal static string Genus_LightBoots1 {
            get {
                return ResourceManager.GetString("Genus_LightBoots1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boots ähnelt.
        /// </summary>
        internal static string Genus_LightBoots2 {
            get {
                return ResourceManager.GetString("Genus_LightBoots2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Armor ähnelt.
        /// </summary>
        internal static string Genus_LightChest0 {
            get {
                return ResourceManager.GetString("Genus_LightChest0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vest ähnelt.
        /// </summary>
        internal static string Genus_LightChest1 {
            get {
                return ResourceManager.GetString("Genus_LightChest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuirass ähnelt.
        /// </summary>
        internal static string Genus_LightChest2 {
            get {
                return ResourceManager.GetString("Genus_LightChest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_LightGloves0 {
            get {
                return ResourceManager.GetString("Genus_LightGloves0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gloves ähnelt.
        /// </summary>
        internal static string Genus_LightGloves1 {
            get {
                return ResourceManager.GetString("Genus_LightGloves1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitts ähnelt.
        /// </summary>
        internal static string Genus_LightGloves2 {
            get {
                return ResourceManager.GetString("Genus_LightGloves2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_LightHelmet0 {
            get {
                return ResourceManager.GetString("Genus_LightHelmet0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cap ähnelt.
        /// </summary>
        internal static string Genus_LightHelmet1 {
            get {
                return ResourceManager.GetString("Genus_LightHelmet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hood ähnelt.
        /// </summary>
        internal static string Genus_LightHelmet2 {
            get {
                return ResourceManager.GetString("Genus_LightHelmet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Shield ähnelt.
        /// </summary>
        internal static string Genus_LightShield0 {
            get {
                return ResourceManager.GetString("Genus_LightShield0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buckler ähnelt.
        /// </summary>
        internal static string Genus_LightShield1 {
            get {
                return ResourceManager.GetString("Genus_LightShield1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Round Shield ähnelt.
        /// </summary>
        internal static string Genus_LightShield2 {
            get {
                return ResourceManager.GetString("Genus_LightShield2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_LongSword0 {
            get {
                return ResourceManager.GetString("Genus_LongSword0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Broad Sword ähnelt.
        /// </summary>
        internal static string Genus_LongSword1 {
            get {
                return ResourceManager.GetString("Genus_LongSword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_LongSword2 {
            get {
                return ResourceManager.GetString("Genus_LongSword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axe ähnelt.
        /// </summary>
        internal static string Genus_OneHandAxe0 {
            get {
                return ResourceManager.GetString("Genus_OneHandAxe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hatchet ähnelt.
        /// </summary>
        internal static string Genus_OneHandAxe1 {
            get {
                return ResourceManager.GetString("Genus_OneHandAxe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die War Cleaver ähnelt.
        /// </summary>
        internal static string Genus_OneHandAxe2 {
            get {
                return ResourceManager.GetString("Genus_OneHandAxe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Club ähnelt.
        /// </summary>
        internal static string Genus_OneHandMace0 {
            get {
                return ResourceManager.GetString("Genus_OneHandMace0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mace ähnelt.
        /// </summary>
        internal static string Genus_OneHandMace1 {
            get {
                return ResourceManager.GetString("Genus_OneHandMace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Morning Star ähnelt.
        /// </summary>
        internal static string Genus_OneHandMace2 {
            get {
                return ResourceManager.GetString("Genus_OneHandMace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_Polearm0 {
            get {
                return ResourceManager.GetString("Genus_Polearm0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Halberd ähnelt.
        /// </summary>
        internal static string Genus_Polearm1 {
            get {
                return ResourceManager.GetString("Genus_Polearm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_Polearm2 {
            get {
                return ResourceManager.GetString("Genus_Polearm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_ShortSword0 {
            get {
                return ResourceManager.GetString("Genus_ShortSword0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Sword ähnelt.
        /// </summary>
        internal static string Genus_ShortSword1 {
            get {
                return ResourceManager.GetString("Genus_ShortSword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cutlass ähnelt.
        /// </summary>
        internal static string Genus_ShortSword2 {
            get {
                return ResourceManager.GetString("Genus_ShortSword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spear ähnelt.
        /// </summary>
        internal static string Genus_Spear0 {
            get {
                return ResourceManager.GetString("Genus_Spear0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hunting Spear ähnelt.
        /// </summary>
        internal static string Genus_Spear1 {
            get {
                return ResourceManager.GetString("Genus_Spear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die War Pike ähnelt.
        /// </summary>
        internal static string Genus_Spear2 {
            get {
                return ResourceManager.GetString("Genus_Spear2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_TwoHandAxe0 {
            get {
                return ResourceManager.GetString("Genus_TwoHandAxe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battle Axe ähnelt.
        /// </summary>
        internal static string Genus_TwoHandAxe1 {
            get {
                return ResourceManager.GetString("Genus_TwoHandAxe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_TwoHandAxe2 {
            get {
                return ResourceManager.GetString("Genus_TwoHandAxe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_TwoHandMace0 {
            get {
                return ResourceManager.GetString("Genus_TwoHandMace0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warhammer ähnelt.
        /// </summary>
        internal static string Genus_TwoHandMace1 {
            get {
                return ResourceManager.GetString("Genus_TwoHandMace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Genus_TwoHandMace2 {
            get {
                return ResourceManager.GetString("Genus_TwoHandMace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sword ähnelt.
        /// </summary>
        internal static string Genus_TwoHandSword0 {
            get {
                return ResourceManager.GetString("Genus_TwoHandSword0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bastard Sword ähnelt.
        /// </summary>
        internal static string Genus_TwoHandSword1 {
            get {
                return ResourceManager.GetString("Genus_TwoHandSword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Curved Sword ähnelt.
        /// </summary>
        internal static string Genus_TwoHandSword2 {
            get {
                return ResourceManager.GetString("Genus_TwoHandSword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leather ähnelt.
        /// </summary>
        internal static string Material_L1 {
            get {
                return ResourceManager.GetString("Material_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hard Leather ähnelt.
        /// </summary>
        internal static string Material_L2 {
            get {
                return ResourceManager.GetString("Material_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elven ähnelt.
        /// </summary>
        internal static string Material_L3 {
            get {
                return ResourceManager.GetString("Material_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dragonhide ähnelt.
        /// </summary>
        internal static string Material_L4 {
            get {
                return ResourceManager.GetString("Material_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iron ähnelt.
        /// </summary>
        internal static string Material_M1 {
            get {
                return ResourceManager.GetString("Material_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steel ähnelt.
        /// </summary>
        internal static string Material_M2 {
            get {
                return ResourceManager.GetString("Material_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dwarven ähnelt.
        /// </summary>
        internal static string Material_M3 {
            get {
                return ResourceManager.GetString("Material_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orichalcum ähnelt.
        /// </summary>
        internal static string Material_M4 {
            get {
                return ResourceManager.GetString("Material_M4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple ähnelt.
        /// </summary>
        internal static string Material_Simple {
            get {
                return ResourceManager.GetString("Material_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Birch ähnelt.
        /// </summary>
        internal static string Material_W1 {
            get {
                return ResourceManager.GetString("Material_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oak ähnelt.
        /// </summary>
        internal static string Material_W2 {
            get {
                return ResourceManager.GetString("Material_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ash ähnelt.
        /// </summary>
        internal static string Material_W3 {
            get {
                return ResourceManager.GetString("Material_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ebony ähnelt.
        /// </summary>
        internal static string Material_W4 {
            get {
                return ResourceManager.GetString("Material_W4", resourceCulture);
            }
        }
    }
}
