//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crafting ähnelt.
        /// </summary>
        internal static string ABL_CRAFT {
            get {
                return ResourceManager.GetString("ABL_CRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axe ähnelt.
        /// </summary>
        internal static string AXE {
            get {
                return ResourceManager.GetString("AXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axe ähnelt.
        /// </summary>
        internal static string AXE0 {
            get {
                return ResourceManager.GetString("AXE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hatchet ähnelt.
        /// </summary>
        internal static string AXE1 {
            get {
                return ResourceManager.GetString("AXE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battle Axe ähnelt.
        /// </summary>
        internal static string AXE2 {
            get {
                return ResourceManager.GetString("AXE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die War Cleaver ähnelt.
        /// </summary>
        internal static string AXE3 {
            get {
                return ResourceManager.GetString("AXE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bear ähnelt.
        /// </summary>
        internal static string BEAR {
            get {
                return ResourceManager.GetString("BEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desert ähnelt.
        /// </summary>
        internal static string BIOME_DESERT {
            get {
                return ResourceManager.GetString("BIOME_DESERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dungeon ähnelt.
        /// </summary>
        internal static string BIOME_DUNGEON {
            get {
                return ResourceManager.GetString("BIOME_DUNGEON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest ähnelt.
        /// </summary>
        internal static string BIOME_FOREST {
            get {
                return ResourceManager.GetString("BIOME_FOREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grassland ähnelt.
        /// </summary>
        internal static string BIOME_GRASSLAND {
            get {
                return ResourceManager.GetString("BIOME_GRASSLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icy Desert ähnelt.
        /// </summary>
        internal static string BIOME_ICE {
            get {
                return ResourceManager.GetString("BIOME_ICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oasis ähnelt.
        /// </summary>
        internal static string BIOME_OASIS {
            get {
                return ResourceManager.GetString("BIOME_OASIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rainforest ähnelt.
        /// </summary>
        internal static string BIOME_RAINFOREST {
            get {
                return ResourceManager.GetString("BIOME_RAINFOREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Savannah ähnelt.
        /// </summary>
        internal static string BIOME_SAVANNAH {
            get {
                return ResourceManager.GetString("BIOME_SAVANNAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swamp ähnelt.
        /// </summary>
        internal static string BIOME_SWAMP {
            get {
                return ResourceManager.GetString("BIOME_SWAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tundra ähnelt.
        /// </summary>
        internal static string BIOME_TUNDRA {
            get {
                return ResourceManager.GetString("BIOME_TUNDRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wasteland ähnelt.
        /// </summary>
        internal static string BIOME_WASTELAND {
            get {
                return ResourceManager.GetString("BIOME_WASTELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blunt Weapon ähnelt.
        /// </summary>
        internal static string BLN {
            get {
                return ResourceManager.GetString("BLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Club ähnelt.
        /// </summary>
        internal static string BLN0 {
            get {
                return ResourceManager.GetString("BLN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mace ähnelt.
        /// </summary>
        internal static string BLN1 {
            get {
                return ResourceManager.GetString("BLN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warhammer ähnelt.
        /// </summary>
        internal static string BLN2 {
            get {
                return ResourceManager.GetString("BLN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Morning Star ähnelt.
        /// </summary>
        internal static string BLN3 {
            get {
                return ResourceManager.GetString("BLN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wild Boar ähnelt.
        /// </summary>
        internal static string BOAR {
            get {
                return ResourceManager.GetString("BOAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grand Wizard of the Order ähnelt.
        /// </summary>
        internal static string BOSS_CULTLEADER {
            get {
                return ResourceManager.GetString("BOSS_CULTLEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demonic Avatar ähnelt.
        /// </summary>
        internal static string BOSS_FINAL_DEMON {
            get {
                return ResourceManager.GetString("BOSS_FINAL_DEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant Rat ähnelt.
        /// </summary>
        internal static string BOSS_GIANTRAT {
            get {
                return ResourceManager.GetString("BOSS_GIANTRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distant Traveller ähnelt.
        /// </summary>
        internal static string BOSS_HEINRICH {
            get {
                return ResourceManager.GetString("BOSS_HEINRICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Centurion ähnelt.
        /// </summary>
        internal static string BOSS_MERCENARY {
            get {
                return ResourceManager.GetString("BOSS_MERCENARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Necromancer ähnelt.
        /// </summary>
        internal static string BOSS_NECROMANCER {
            get {
                return ResourceManager.GetString("BOSS_NECROMANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whitefish Leviathan ähnelt.
        /// </summary>
        internal static string BOSS_RENKE {
            get {
                return ResourceManager.GetString("BOSS_RENKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Salty Archmage ähnelt.
        /// </summary>
        internal static string BOSS_SOREN {
            get {
                return ResourceManager.GetString("BOSS_SOREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priest of the Void ähnelt.
        /// </summary>
        internal static string BOSS_VOIDPRIEST {
            get {
                return ResourceManager.GetString("BOSS_VOIDPRIEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viking ähnelt.
        /// </summary>
        internal static string CLASS_AXE_HAR {
            get {
                return ResourceManager.GetString("CLASS_AXE_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warrior ähnelt.
        /// </summary>
        internal static string CLASS_AXE_LAR {
            get {
                return ResourceManager.GetString("CLASS_AXE_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berserker ähnelt.
        /// </summary>
        internal static string CLASS_AXE_X {
            get {
                return ResourceManager.GetString("CLASS_AXE_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paladin ähnelt.
        /// </summary>
        internal static string CLASS_BLN_HAR {
            get {
                return ResourceManager.GetString("CLASS_BLN_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Militia ähnelt.
        /// </summary>
        internal static string CLASS_BLN_LAR {
            get {
                return ResourceManager.GetString("CLASS_BLN_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warrior Monk ähnelt.
        /// </summary>
        internal static string CLASS_BLN_X {
            get {
                return ResourceManager.GetString("CLASS_BLN_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adventurer ähnelt.
        /// </summary>
        internal static string CLASS_DEFAULT {
            get {
                return ResourceManager.GetString("CLASS_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knight ähnelt.
        /// </summary>
        internal static string CLASS_LBL_HAR {
            get {
                return ResourceManager.GetString("CLASS_LBL_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Samurai ähnelt.
        /// </summary>
        internal static string CLASS_LBL_LAR {
            get {
                return ResourceManager.GetString("CLASS_LBL_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kensai ähnelt.
        /// </summary>
        internal static string CLASS_LBL_X {
            get {
                return ResourceManager.GetString("CLASS_LBL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hoplite ähnelt.
        /// </summary>
        internal static string CLASS_POL_HAR {
            get {
                return ResourceManager.GetString("CLASS_POL_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ranger ähnelt.
        /// </summary>
        internal static string CLASS_POL_LAR {
            get {
                return ResourceManager.GetString("CLASS_POL_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hunter ähnelt.
        /// </summary>
        internal static string CLASS_POL_X {
            get {
                return ResourceManager.GetString("CLASS_POL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legionnaire ähnelt.
        /// </summary>
        internal static string CLASS_SBL_HAR {
            get {
                return ResourceManager.GetString("CLASS_SBL_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ninja ähnelt.
        /// </summary>
        internal static string CLASS_SBL_LAR {
            get {
                return ResourceManager.GetString("CLASS_SBL_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thief ähnelt.
        /// </summary>
        internal static string CLASS_SBL_X {
            get {
                return ResourceManager.GetString("CLASS_SBL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brawler ähnelt.
        /// </summary>
        internal static string CLASS_X_HAR {
            get {
                return ResourceManager.GetString("CLASS_X_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Martial Artist ähnelt.
        /// </summary>
        internal static string CLASS_X_LAR {
            get {
                return ResourceManager.GetString("CLASS_X_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monk ähnelt.
        /// </summary>
        internal static string CLASS_X_X {
            get {
                return ResourceManager.GetString("CLASS_X_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dragon ähnelt.
        /// </summary>
        internal static string DRAGON {
            get {
                return ResourceManager.GetString("DRAGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big Dragon ähnelt.
        /// </summary>
        internal static string DRAGON2 {
            get {
                return ResourceManager.GetString("DRAGON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bigger Dragon ähnelt.
        /// </summary>
        internal static string DRAGON3 {
            get {
                return ResourceManager.GetString("DRAGON3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dual Wielding ähnelt.
        /// </summary>
        internal static string DualWield {
            get {
                return ResourceManager.GetString("DualWield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Dummy ähnelt.
        /// </summary>
        internal static string DUMMY {
            get {
                return ResourceManager.GetString("DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gloves ähnelt.
        /// </summary>
        internal static string Equip_ArmArmor {
            get {
                return ResourceManager.GetString("Equip_ArmArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Body Armor ähnelt.
        /// </summary>
        internal static string Equip_ChestArmor {
            get {
                return ResourceManager.GetString("Equip_ChestArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helmet ähnelt.
        /// </summary>
        internal static string Equip_HeadArmor {
            get {
                return ResourceManager.GetString("Equip_HeadArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boots ähnelt.
        /// </summary>
        internal static string Equip_LegArmor {
            get {
                return ResourceManager.GetString("Equip_LegArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield ähnelt.
        /// </summary>
        internal static string Equip_Shield {
            get {
                return ResourceManager.GetString("Equip_Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon ähnelt.
        /// </summary>
        internal static string Equip_Weapon {
            get {
                return ResourceManager.GetString("Equip_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Armor ähnelt.
        /// </summary>
        internal static string HAR {
            get {
                return ResourceManager.GetString("HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Armor ähnelt.
        /// </summary>
        internal static string HAR0 {
            get {
                return ResourceManager.GetString("HAR0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chain Mail ähnelt.
        /// </summary>
        internal static string HAR1 {
            get {
                return ResourceManager.GetString("HAR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tower Shield ähnelt.
        /// </summary>
        internal static string HAR10 {
            get {
                return ResourceManager.GetString("HAR10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helmet ähnelt.
        /// </summary>
        internal static string HAR2 {
            get {
                return ResourceManager.GetString("HAR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chain Gloves ähnelt.
        /// </summary>
        internal static string HAR3 {
            get {
                return ResourceManager.GetString("HAR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chain Boots ähnelt.
        /// </summary>
        internal static string HAR4 {
            get {
                return ResourceManager.GetString("HAR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kite Shield ähnelt.
        /// </summary>
        internal static string HAR5 {
            get {
                return ResourceManager.GetString("HAR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breast Plate ähnelt.
        /// </summary>
        internal static string HAR6 {
            get {
                return ResourceManager.GetString("HAR6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full Helm ähnelt.
        /// </summary>
        internal static string HAR7 {
            get {
                return ResourceManager.GetString("HAR7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gauntlets ähnelt.
        /// </summary>
        internal static string HAR8 {
            get {
                return ResourceManager.GetString("HAR8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greaves ähnelt.
        /// </summary>
        internal static string HAR9 {
            get {
                return ResourceManager.GetString("HAR9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Armor ähnelt.
        /// </summary>
        internal static string LAR {
            get {
                return ResourceManager.GetString("LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Armor ähnelt.
        /// </summary>
        internal static string LAR0 {
            get {
                return ResourceManager.GetString("LAR0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surcoat ähnelt.
        /// </summary>
        internal static string LAR1 {
            get {
                return ResourceManager.GetString("LAR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Round Shield ähnelt.
        /// </summary>
        internal static string LAR10 {
            get {
                return ResourceManager.GetString("LAR10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hood ähnelt.
        /// </summary>
        internal static string LAR2 {
            get {
                return ResourceManager.GetString("LAR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gloves ähnelt.
        /// </summary>
        internal static string LAR3 {
            get {
                return ResourceManager.GetString("LAR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shoes ähnelt.
        /// </summary>
        internal static string LAR4 {
            get {
                return ResourceManager.GetString("LAR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buckler ähnelt.
        /// </summary>
        internal static string LAR5 {
            get {
                return ResourceManager.GetString("LAR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuirass ähnelt.
        /// </summary>
        internal static string LAR6 {
            get {
                return ResourceManager.GetString("LAR6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helmet ähnelt.
        /// </summary>
        internal static string LAR7 {
            get {
                return ResourceManager.GetString("LAR7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mitts ähnelt.
        /// </summary>
        internal static string LAR8 {
            get {
                return ResourceManager.GetString("LAR8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boots ähnelt.
        /// </summary>
        internal static string LAR9 {
            get {
                return ResourceManager.GetString("LAR9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Blade ähnelt.
        /// </summary>
        internal static string LBL {
            get {
                return ResourceManager.GetString("LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sword ähnelt.
        /// </summary>
        internal static string LBL0 {
            get {
                return ResourceManager.GetString("LBL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Sword ähnelt.
        /// </summary>
        internal static string LBL1 {
            get {
                return ResourceManager.GetString("LBL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed Sword ähnelt.
        /// </summary>
        internal static string LBL2 {
            get {
                return ResourceManager.GetString("LBL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Curved Sword ähnelt.
        /// </summary>
        internal static string LBL3 {
            get {
                return ResourceManager.GetString("LBL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leather ähnelt.
        /// </summary>
        internal static string MAT_L0 {
            get {
                return ResourceManager.GetString("MAT_L0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hard Leather ähnelt.
        /// </summary>
        internal static string MAT_L1 {
            get {
                return ResourceManager.GetString("MAT_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elvish ähnelt.
        /// </summary>
        internal static string MAT_L2 {
            get {
                return ResourceManager.GetString("MAT_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iron ähnelt.
        /// </summary>
        internal static string MAT_M0 {
            get {
                return ResourceManager.GetString("MAT_M0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steel ähnelt.
        /// </summary>
        internal static string MAT_M1 {
            get {
                return ResourceManager.GetString("MAT_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dwarven ähnelt.
        /// </summary>
        internal static string MAT_M2 {
            get {
                return ResourceManager.GetString("MAT_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple ähnelt.
        /// </summary>
        internal static string MAT_SIMPLE {
            get {
                return ResourceManager.GetString("MAT_SIMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beech ähnelt.
        /// </summary>
        internal static string MAT_W0 {
            get {
                return ResourceManager.GetString("MAT_W0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oak ähnelt.
        /// </summary>
        internal static string MAT_W1 {
            get {
                return ResourceManager.GetString("MAT_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ash ähnelt.
        /// </summary>
        internal static string MAT_W2 {
            get {
                return ResourceManager.GetString("MAT_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abomination ähnelt.
        /// </summary>
        internal static string MOB_ABOMINATION {
            get {
                return ResourceManager.GetString("MOB_ABOMINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Machine ähnelt.
        /// </summary>
        internal static string MOB_ANCIENTMACHINE {
            get {
                return ResourceManager.GetString("MOB_ANCIENTMACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assassin ähnelt.
        /// </summary>
        internal static string MOB_ASSASSIN {
            get {
                return ResourceManager.GetString("MOB_ASSASSIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big Rat ähnelt.
        /// </summary>
        internal static string MOB_BIGRAT {
            get {
                return ResourceManager.GetString("MOB_BIGRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cultist ähnelt.
        /// </summary>
        internal static string MOB_CULTIST {
            get {
                return ResourceManager.GetString("MOB_CULTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knight of the Order ähnelt.
        /// </summary>
        internal static string MOB_CULTKNIGHT {
            get {
                return ResourceManager.GetString("MOB_CULTKNIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep One ähnelt.
        /// </summary>
        internal static string MOB_DEEPONE {
            get {
                return ResourceManager.GetString("MOB_DEEPONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Deep One ähnelt.
        /// </summary>
        internal static string MOB_DEEPONE2 {
            get {
                return ResourceManager.GetString("MOB_DEEPONE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Winged Demon ähnelt.
        /// </summary>
        internal static string MOB_DEMON1 {
            get {
                return ResourceManager.GetString("MOB_DEMON1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bigger Imp ähnelt.
        /// </summary>
        internal static string MOB_DEMON2 {
            get {
                return ResourceManager.GetString("MOB_DEMON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fanatic ähnelt.
        /// </summary>
        internal static string MOB_FANATIC {
            get {
                return ResourceManager.GetString("MOB_FANATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greater Demon of the Void ähnelt.
        /// </summary>
        internal static string MOB_GREATERDEMON {
            get {
                return ResourceManager.GetString("MOB_GREATERDEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gryphon Rider ähnelt.
        /// </summary>
        internal static string MOB_GRYPHON {
            get {
                return ResourceManager.GetString("MOB_GRYPHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angry Badger ähnelt.
        /// </summary>
        internal static string MOB_HUFFLE {
            get {
                return ResourceManager.GetString("MOB_HUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imp ähnelt.
        /// </summary>
        internal static string MOB_IMP {
            get {
                return ResourceManager.GetString("MOB_IMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lesser Demon of the Void ähnelt.
        /// </summary>
        internal static string MOB_LESSERDEMON {
            get {
                return ResourceManager.GetString("MOB_LESSERDEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Martial Artist ähnelt.
        /// </summary>
        internal static string MOB_MARTIALARTIST {
            get {
                return ResourceManager.GetString("MOB_MARTIALARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Legionnaire ähnelt.
        /// </summary>
        internal static string MOB_MERCENARY {
            get {
                return ResourceManager.GetString("MOB_MERCENARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rat ähnelt.
        /// </summary>
        internal static string MOB_RAT {
            get {
                return ResourceManager.GetString("MOB_RAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raven ähnelt.
        /// </summary>
        internal static string MOB_RAVEN {
            get {
                return ResourceManager.GetString("MOB_RAVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shark ähnelt.
        /// </summary>
        internal static string MOB_SHARK {
            get {
                return ResourceManager.GetString("MOB_SHARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skeleton ähnelt.
        /// </summary>
        internal static string MOB_SKELETON {
            get {
                return ResourceManager.GetString("MOB_SKELETON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snake Charmer ähnelt.
        /// </summary>
        internal static string MOB_SNAKE {
            get {
                return ResourceManager.GetString("MOB_SNAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terracotta Guard ähnelt.
        /// </summary>
        internal static string MOB_TERRACOTTA {
            get {
                return ResourceManager.GetString("MOB_TERRACOTTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terracotta General ähnelt.
        /// </summary>
        internal static string MOB_TERRACOTTA2 {
            get {
                return ResourceManager.GetString("MOB_TERRACOTTA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Void Infused Cultist ähnelt.
        /// </summary>
        internal static string MOB_VOIDCULTIST {
            get {
                return ResourceManager.GetString("MOB_VOIDCULTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Void Fiend ähnelt.
        /// </summary>
        internal static string MOB_VOIDFIEND {
            get {
                return ResourceManager.GetString("MOB_VOIDFIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warlock ähnelt.
        /// </summary>
        internal static string MOB_WARLOCK {
            get {
                return ResourceManager.GetString("MOB_WARLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zombie ähnelt.
        /// </summary>
        internal static string MOB_ZOMBIE {
            get {
                return ResourceManager.GetString("MOB_ZOMBIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ogre ähnelt.
        /// </summary>
        internal static string OGRE {
            get {
                return ResourceManager.GetString("OGRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polearm ähnelt.
        /// </summary>
        internal static string POL {
            get {
                return ResourceManager.GetString("POL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spear ähnelt.
        /// </summary>
        internal static string POL0 {
            get {
                return ResourceManager.GetString("POL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Halberd ähnelt.
        /// </summary>
        internal static string POL1 {
            get {
                return ResourceManager.GetString("POL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hunting Spear ähnelt.
        /// </summary>
        internal static string POL2 {
            get {
                return ResourceManager.GetString("POL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die War Pike ähnelt.
        /// </summary>
        internal static string POL3 {
            get {
                return ResourceManager.GetString("POL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Blade ähnelt.
        /// </summary>
        internal static string SBL {
            get {
                return ResourceManager.GetString("SBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knife ähnelt.
        /// </summary>
        internal static string SBL0 {
            get {
                return ResourceManager.GetString("SBL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dagger ähnelt.
        /// </summary>
        internal static string SBL1 {
            get {
                return ResourceManager.GetString("SBL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Sword ähnelt.
        /// </summary>
        internal static string SBL2 {
            get {
                return ResourceManager.GetString("SBL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cutlass ähnelt.
        /// </summary>
        internal static string SBL3 {
            get {
                return ResourceManager.GetString("SBL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At the threshold between worlds you encounter the demonic champion. As you clash, time and space appear to to twist around you until everything just... stops.
        ///
        ///Time to finish: {0} ähnelt.
        /// </summary>
        internal static string STORY_END_TEXT {
            get {
                return ResourceManager.GetString("STORY_END_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convergence ähnelt.
        /// </summary>
        internal static string STORY_END_TITLE {
            get {
                return ResourceManager.GetString("STORY_END_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wolf ähnelt.
        /// </summary>
        internal static string WOLF {
            get {
                return ResourceManager.GetString("WOLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wyvern ähnelt.
        /// </summary>
        internal static string WYVERN {
            get {
                return ResourceManager.GetString("WYVERN", resourceCulture);
            }
        }
    }
}
