//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die experience gain ähnelt.
        /// </summary>
        internal static string AbilityXpGain {
            get {
                return ResourceManager.GetString("AbilityXpGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crafting ähnelt.
        /// </summary>
        internal static string ABL_CRAFT {
            get {
                return ResourceManager.GetString("ABL_CRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two Weapons ähnelt.
        /// </summary>
        internal static string ABL_DUALWIELD {
            get {
                return ResourceManager.GetString("ABL_DUALWIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shielded ähnelt.
        /// </summary>
        internal static string ABL_SHIELDED {
            get {
                return ResourceManager.GetString("ABL_SHIELDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single-Handed ähnelt.
        /// </summary>
        internal static string ABL_SINGLEHANDED {
            get {
                return ResourceManager.GetString("ABL_SINGLEHANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed ähnelt.
        /// </summary>
        internal static string ABL_TWOHANDED {
            get {
                return ResourceManager.GetString("ABL_TWOHANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Craft(s) ähnelt.
        /// </summary>
        internal static string ActiveCraftingSlot {
            get {
                return ResourceManager.GetString("ActiveCraftingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armor Rating ähnelt.
        /// </summary>
        internal static string ArmorRating {
            get {
                return ResourceManager.GetString("ArmorRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attack Speed ähnelt.
        /// </summary>
        internal static string AttackSpeed {
            get {
                return ResourceManager.GetString("AttackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axe ähnelt.
        /// </summary>
        internal static string AXE {
            get {
                return ResourceManager.GetString("AXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coast ähnelt.
        /// </summary>
        internal static string BIOME_COAST {
            get {
                return ResourceManager.GetString("BIOME_COAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desert ähnelt.
        /// </summary>
        internal static string BIOME_DESERT {
            get {
                return ResourceManager.GetString("BIOME_DESERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dungeon ähnelt.
        /// </summary>
        internal static string BIOME_DUNGEON {
            get {
                return ResourceManager.GetString("BIOME_DUNGEON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Foothills ähnelt.
        /// </summary>
        internal static string BIOME_FOOTHILLS {
            get {
                return ResourceManager.GetString("BIOME_FOOTHILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest ähnelt.
        /// </summary>
        internal static string BIOME_FOREST {
            get {
                return ResourceManager.GetString("BIOME_FOREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grassland ähnelt.
        /// </summary>
        internal static string BIOME_GRASSLAND {
            get {
                return ResourceManager.GetString("BIOME_GRASSLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graveyard ähnelt.
        /// </summary>
        internal static string BIOME_GRAVEYARD {
            get {
                return ResourceManager.GetString("BIOME_GRAVEYARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icy Desert ähnelt.
        /// </summary>
        internal static string BIOME_ICE {
            get {
                return ResourceManager.GetString("BIOME_ICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mountains ähnelt.
        /// </summary>
        internal static string BIOME_MOUNTAINS {
            get {
                return ResourceManager.GetString("BIOME_MOUNTAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oasis ähnelt.
        /// </summary>
        internal static string BIOME_OASIS {
            get {
                return ResourceManager.GetString("BIOME_OASIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rainforest ähnelt.
        /// </summary>
        internal static string BIOME_RAINFOREST {
            get {
                return ResourceManager.GetString("BIOME_RAINFOREST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Savannah ähnelt.
        /// </summary>
        internal static string BIOME_SAVANNAH {
            get {
                return ResourceManager.GetString("BIOME_SAVANNAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summit ähnelt.
        /// </summary>
        internal static string BIOME_SUMMIT {
            get {
                return ResourceManager.GetString("BIOME_SUMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swamp ähnelt.
        /// </summary>
        internal static string BIOME_SWAMP {
            get {
                return ResourceManager.GetString("BIOME_SWAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tundra ähnelt.
        /// </summary>
        internal static string BIOME_TUNDRA {
            get {
                return ResourceManager.GetString("BIOME_TUNDRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wasteland ähnelt.
        /// </summary>
        internal static string BIOME_WASTELAND {
            get {
                return ResourceManager.GetString("BIOME_WASTELAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blunt Weapon ähnelt.
        /// </summary>
        internal static string BLN {
            get {
                return ResourceManager.GetString("BLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die experience gain ähnelt.
        /// </summary>
        internal static string CharacterXpGain {
            get {
                return ResourceManager.GetString("CharacterXpGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viking ähnelt.
        /// </summary>
        internal static string CLASS_AXE_HAR {
            get {
                return ResourceManager.GetString("CLASS_AXE_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warrior ähnelt.
        /// </summary>
        internal static string CLASS_AXE_LAR {
            get {
                return ResourceManager.GetString("CLASS_AXE_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berserker ähnelt.
        /// </summary>
        internal static string CLASS_AXE_X {
            get {
                return ResourceManager.GetString("CLASS_AXE_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paladin ähnelt.
        /// </summary>
        internal static string CLASS_BLN_HAR {
            get {
                return ResourceManager.GetString("CLASS_BLN_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barbarian ähnelt.
        /// </summary>
        internal static string CLASS_BLN_LAR {
            get {
                return ResourceManager.GetString("CLASS_BLN_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warrior Monk ähnelt.
        /// </summary>
        internal static string CLASS_BLN_X {
            get {
                return ResourceManager.GetString("CLASS_BLN_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adventurer ähnelt.
        /// </summary>
        internal static string CLASS_DEFAULT {
            get {
                return ResourceManager.GetString("CLASS_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knight ähnelt.
        /// </summary>
        internal static string CLASS_LBL_HAR {
            get {
                return ResourceManager.GetString("CLASS_LBL_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Samurai ähnelt.
        /// </summary>
        internal static string CLASS_LBL_LAR {
            get {
                return ResourceManager.GetString("CLASS_LBL_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kensai ähnelt.
        /// </summary>
        internal static string CLASS_LBL_X {
            get {
                return ResourceManager.GetString("CLASS_LBL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hoplite ähnelt.
        /// </summary>
        internal static string CLASS_POL_HAR {
            get {
                return ResourceManager.GetString("CLASS_POL_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ranger ähnelt.
        /// </summary>
        internal static string CLASS_POL_LAR {
            get {
                return ResourceManager.GetString("CLASS_POL_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hunter ähnelt.
        /// </summary>
        internal static string CLASS_POL_X {
            get {
                return ResourceManager.GetString("CLASS_POL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legionnaire ähnelt.
        /// </summary>
        internal static string CLASS_SBL_HAR {
            get {
                return ResourceManager.GetString("CLASS_SBL_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ninja ähnelt.
        /// </summary>
        internal static string CLASS_SBL_LAR {
            get {
                return ResourceManager.GetString("CLASS_SBL_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thief ähnelt.
        /// </summary>
        internal static string CLASS_SBL_X {
            get {
                return ResourceManager.GetString("CLASS_SBL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brawler ähnelt.
        /// </summary>
        internal static string CLASS_X_HAR {
            get {
                return ResourceManager.GetString("CLASS_X_HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Martial Artist ähnelt.
        /// </summary>
        internal static string CLASS_X_LAR {
            get {
                return ResourceManager.GetString("CLASS_X_LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monk ähnelt.
        /// </summary>
        internal static string CLASS_X_X {
            get {
                return ResourceManager.GetString("CLASS_X_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crafting cost efficiency ähnelt.
        /// </summary>
        internal static string CraftingCostEfficiency {
            get {
                return ResourceManager.GetString("CraftingCostEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crafting Slot(s) ähnelt.
        /// </summary>
        internal static string CraftingSlot {
            get {
                return ResourceManager.GetString("CraftingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crafting Speed ähnelt.
        /// </summary>
        internal static string CraftingSpeed {
            get {
                return ResourceManager.GetString("CraftingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die using two weapons ähnelt.
        /// </summary>
        internal static string DualWield {
            get {
                return ResourceManager.GetString("DualWield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gloves ähnelt.
        /// </summary>
        internal static string Equip_ArmArmor {
            get {
                return ResourceManager.GetString("Equip_ArmArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Body Armor ähnelt.
        /// </summary>
        internal static string Equip_ChestArmor {
            get {
                return ResourceManager.GetString("Equip_ChestArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helmet ähnelt.
        /// </summary>
        internal static string Equip_HeadArmor {
            get {
                return ResourceManager.GetString("Equip_HeadArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boots ähnelt.
        /// </summary>
        internal static string Equip_LegArmor {
            get {
                return ResourceManager.GetString("Equip_LegArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield ähnelt.
        /// </summary>
        internal static string Equip_Shield {
            get {
                return ResourceManager.GetString("Equip_Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon ähnelt.
        /// </summary>
        internal static string Equip_Weapon {
            get {
                return ResourceManager.GetString("Equip_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Evasion Rating ähnelt.
        /// </summary>
        internal static string EvasionRating {
            get {
                return ResourceManager.GetString("EvasionRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Strike ähnelt.
        /// </summary>
        internal static string FirstStrike {
            get {
                return ResourceManager.GetString("FirstStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die global ähnelt.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Armor ähnelt.
        /// </summary>
        internal static string HAR {
            get {
                return ResourceManager.GetString("HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Armor ähnelt.
        /// </summary>
        internal static string LAR {
            get {
                return ResourceManager.GetString("LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Blade ähnelt.
        /// </summary>
        internal static string LBL {
            get {
                return ResourceManager.GetString("LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die local ähnelt.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main Hand ähnelt.
        /// </summary>
        internal static string MainHand {
            get {
                return ResourceManager.GetString("MainHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offhand ähnelt.
        /// </summary>
        internal static string OffHand {
            get {
                return ResourceManager.GetString("OffHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polearm ähnelt.
        /// </summary>
        internal static string POL {
            get {
                return ResourceManager.GetString("POL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Blade ähnelt.
        /// </summary>
        internal static string SBL {
            get {
                return ResourceManager.GetString("SBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die using a shield ähnelt.
        /// </summary>
        internal static string Shielded {
            get {
                return ResourceManager.GetString("Shielded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fighting single-handed ähnelt.
        /// </summary>
        internal static string SingleHanded {
            get {
                return ResourceManager.GetString("SingleHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At the threshold between worlds you encounter the demonic champion. As you clash, time and space appear to to twist around you until everything just... stops.
        ///
        ///Time to finish: {0} ähnelt.
        /// </summary>
        internal static string STORY_END_TEXT {
            get {
                return ResourceManager.GetString("STORY_END_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convergence ähnelt.
        /// </summary>
        internal static string STORY_END_TITLE {
            get {
                return ResourceManager.GetString("STORY_END_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Limit ähnelt.
        /// </summary>
        internal static string TimeShield {
            get {
                return ResourceManager.GetString("TimeShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conqueror ähnelt.
        /// </summary>
        internal static string Title_Conqueror {
            get {
                return ResourceManager.GetString("Title_Conqueror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exalted Conqueror ähnelt.
        /// </summary>
        internal static string Title_ConquerorHC {
            get {
                return ResourceManager.GetString("Title_ConquerorHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the Patient ähnelt.
        /// </summary>
        internal static string Title_Patient {
            get {
                return ResourceManager.GetString("Title_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the Prudent ähnelt.
        /// </summary>
        internal static string Title_Prudent {
            get {
                return ResourceManager.GetString("Title_Prudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the Swift ähnelt.
        /// </summary>
        internal static string Title_Swift {
            get {
                return ResourceManager.GetString("Title_Swift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die using a two-handed weapon ähnelt.
        /// </summary>
        internal static string TwoHanded {
            get {
                return ResourceManager.GetString("TwoHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unarmed ähnelt.
        /// </summary>
        internal static string UNARMED {
            get {
                return ResourceManager.GetString("UNARMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unarmored ähnelt.
        /// </summary>
        internal static string UNARMORED {
            get {
                return ResourceManager.GetString("UNARMORED", resourceCulture);
            }
        }
    }
}
