//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axe ähnelt.
        /// </summary>
        internal static string AXE {
            get {
                return ResourceManager.GetString("AXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple Axe ähnelt.
        /// </summary>
        internal static string AXE0 {
            get {
                return ResourceManager.GetString("AXE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hatchet ähnelt.
        /// </summary>
        internal static string AXE1 {
            get {
                return ResourceManager.GetString("AXE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battle Axe ähnelt.
        /// </summary>
        internal static string AXE2 {
            get {
                return ResourceManager.GetString("AXE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bear ähnelt.
        /// </summary>
        internal static string BEAR {
            get {
                return ResourceManager.GetString("BEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blunt Weapon ähnelt.
        /// </summary>
        internal static string BLN {
            get {
                return ResourceManager.GetString("BLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple Club ähnelt.
        /// </summary>
        internal static string BLN0 {
            get {
                return ResourceManager.GetString("BLN0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mace ähnelt.
        /// </summary>
        internal static string BLN1 {
            get {
                return ResourceManager.GetString("BLN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warhammer ähnelt.
        /// </summary>
        internal static string BLN2 {
            get {
                return ResourceManager.GetString("BLN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wild Boar ähnelt.
        /// </summary>
        internal static string BOAR {
            get {
                return ResourceManager.GetString("BOAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grand Wizard of the Order ähnelt.
        /// </summary>
        internal static string BOSS_CULTLEADER {
            get {
                return ResourceManager.GetString("BOSS_CULTLEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Centurion ähnelt.
        /// </summary>
        internal static string BOSS_MERCENARY {
            get {
                return ResourceManager.GetString("BOSS_MERCENARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Necromancer ähnelt.
        /// </summary>
        internal static string BOSS_NECROMANCER {
            get {
                return ResourceManager.GetString("BOSS_NECROMANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priest of the Void ähnelt.
        /// </summary>
        internal static string BOSS_VOIDPRIEST {
            get {
                return ResourceManager.GetString("BOSS_VOIDPRIEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cult&apos;s Stronghold ähnelt.
        /// </summary>
        internal static string CASTLE {
            get {
                return ResourceManager.GetString("CASTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The traiterous lord who had hired the mercenaries has turned his castle into the cult&apos;s base of operations. ähnelt.
        /// </summary>
        internal static string CASTLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("CASTLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Crypt ähnelt.
        /// </summary>
        internal static string CRYPT {
            get {
                return ResourceManager.GetString("CRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is something stirring beneath the graveyard... ähnelt.
        /// </summary>
        internal static string CRYPT_DESCRIPTION {
            get {
                return ResourceManager.GetString("CRYPT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dragon ähnelt.
        /// </summary>
        internal static string DRAGON {
            get {
                return ResourceManager.GetString("DRAGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big Dragon ähnelt.
        /// </summary>
        internal static string DRAGON2 {
            get {
                return ResourceManager.GetString("DRAGON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bigger Dragon ähnelt.
        /// </summary>
        internal static string DRAGON3 {
            get {
                return ResourceManager.GetString("DRAGON3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Dummy ähnelt.
        /// </summary>
        internal static string DUMMY {
            get {
                return ResourceManager.GetString("DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Armor ähnelt.
        /// </summary>
        internal static string HAR {
            get {
                return ResourceManager.GetString("HAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple Heavy Armor ähnelt.
        /// </summary>
        internal static string HAR0 {
            get {
                return ResourceManager.GetString("HAR0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plate Armor ähnelt.
        /// </summary>
        internal static string HAR1 {
            get {
                return ResourceManager.GetString("HAR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Labyrinth ähnelt.
        /// </summary>
        internal static string LABYRINTH {
            get {
                return ResourceManager.GetString("LABYRINTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Below the castle, there is a huge, labyrinthian dungeon. ähnelt.
        /// </summary>
        internal static string LABYRINTH_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABYRINTH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Armor ähnelt.
        /// </summary>
        internal static string LAR {
            get {
                return ResourceManager.GetString("LAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple Light Armor ähnelt.
        /// </summary>
        internal static string LAR0 {
            get {
                return ResourceManager.GetString("LAR0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Padded Armor ähnelt.
        /// </summary>
        internal static string LAR1 {
            get {
                return ResourceManager.GetString("LAR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Blade ähnelt.
        /// </summary>
        internal static string LBL {
            get {
                return ResourceManager.GetString("LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple Sword ähnelt.
        /// </summary>
        internal static string LBL0 {
            get {
                return ResourceManager.GetString("LBL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Sword ähnelt.
        /// </summary>
        internal static string LBL1 {
            get {
                return ResourceManager.GetString("LBL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Claymore ähnelt.
        /// </summary>
        internal static string LBL2 {
            get {
                return ResourceManager.GetString("LBL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Lighthouse ähnelt.
        /// </summary>
        internal static string LIGHTHOUSE {
            get {
                return ResourceManager.GetString("LIGHTHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cultists have holed up in the old lighthouse. The blue flames they lit have attracted more than just ships. ähnelt.
        /// </summary>
        internal static string LIGHTHOUSE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LIGHTHOUSE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Lighthouse II ähnelt.
        /// </summary>
        internal static string LIGHTHOUSE2 {
            get {
                return ResourceManager.GetString("LIGHTHOUSE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While you were fighting the cultists in their castle, their leader has returned to the old lighthouse to complete the ritual. ähnelt.
        /// </summary>
        internal static string LIGHTHOUSE2_DESCRIPTION {
            get {
                return ResourceManager.GetString("LIGHTHOUSE2_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Camp ähnelt.
        /// </summary>
        internal static string MERCCAMP {
            get {
                return ResourceManager.GetString("MERCCAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cultists have acquired the services of a company of human mercenaries. Raiding their camp and killing their leader should drive them away. ähnelt.
        /// </summary>
        internal static string MERCCAMP_DESCRIPTION {
            get {
                return ResourceManager.GetString("MERCCAMP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abomination ähnelt.
        /// </summary>
        internal static string MOB_ABOMINATION {
            get {
                return ResourceManager.GetString("MOB_ABOMINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cultist ähnelt.
        /// </summary>
        internal static string MOB_CULTIST {
            get {
                return ResourceManager.GetString("MOB_CULTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knight of the Order ähnelt.
        /// </summary>
        internal static string MOB_CULTKNIGHT {
            get {
                return ResourceManager.GetString("MOB_CULTKNIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Winged Demon ähnelt.
        /// </summary>
        internal static string MOB_DEMON1 {
            get {
                return ResourceManager.GetString("MOB_DEMON1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bigger Imp ähnelt.
        /// </summary>
        internal static string MOB_DEMON2 {
            get {
                return ResourceManager.GetString("MOB_DEMON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fanatic ähnelt.
        /// </summary>
        internal static string MOB_FANATIC {
            get {
                return ResourceManager.GetString("MOB_FANATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greater Demon of the Void ähnelt.
        /// </summary>
        internal static string MOB_GREATERDEMON {
            get {
                return ResourceManager.GetString("MOB_GREATERDEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imp ähnelt.
        /// </summary>
        internal static string MOB_IMP {
            get {
                return ResourceManager.GetString("MOB_IMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lessor Demon of the Void ähnelt.
        /// </summary>
        internal static string MOB_LESSERDEMON {
            get {
                return ResourceManager.GetString("MOB_LESSERDEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Legionnaire ähnelt.
        /// </summary>
        internal static string MOB_MERCENARY {
            get {
                return ResourceManager.GetString("MOB_MERCENARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skeleton ähnelt.
        /// </summary>
        internal static string MOB_SKELETON {
            get {
                return ResourceManager.GetString("MOB_SKELETON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Void Infused Cultist ähnelt.
        /// </summary>
        internal static string MOB_VOIDCULTIST {
            get {
                return ResourceManager.GetString("MOB_VOIDCULTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Void Fiend ähnelt.
        /// </summary>
        internal static string MOB_VOIDFIEND {
            get {
                return ResourceManager.GetString("MOB_VOIDFIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warlock ähnelt.
        /// </summary>
        internal static string MOB_WARLOCK {
            get {
                return ResourceManager.GetString("MOB_WARLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zombie ähnelt.
        /// </summary>
        internal static string MOB_ZOMBIE {
            get {
                return ResourceManager.GetString("MOB_ZOMBIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ogre ähnelt.
        /// </summary>
        internal static string OGRE {
            get {
                return ResourceManager.GetString("OGRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polearm ähnelt.
        /// </summary>
        internal static string POL {
            get {
                return ResourceManager.GetString("POL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple Spear ähnelt.
        /// </summary>
        internal static string POL0 {
            get {
                return ResourceManager.GetString("POL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Halberd ähnelt.
        /// </summary>
        internal static string POL1 {
            get {
                return ResourceManager.GetString("POL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hunting Spear ähnelt.
        /// </summary>
        internal static string POL2 {
            get {
                return ResourceManager.GetString("POL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Blade ähnelt.
        /// </summary>
        internal static string SBL {
            get {
                return ResourceManager.GetString("SBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simple Knife ähnelt.
        /// </summary>
        internal static string SBL0 {
            get {
                return ResourceManager.GetString("SBL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dagger ähnelt.
        /// </summary>
        internal static string SBL1 {
            get {
                return ResourceManager.GetString("SBL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Sword ähnelt.
        /// </summary>
        internal static string SBL2 {
            get {
                return ResourceManager.GetString("SBL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Temple ähnelt.
        /// </summary>
        internal static string TEMPLE {
            get {
                return ResourceManager.GetString("TEMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cultists have relocated to the catacombs below the ruins of an ancient elven temple. ähnelt.
        /// </summary>
        internal static string TEMPLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEMPLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Threshold ähnelt.
        /// </summary>
        internal static string THRESHOLD {
            get {
                return ResourceManager.GetString("THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We were too late! The ritual has been completed and the gate between the dimensions has been opened. An army of demons is flooding through the rift. Stand fast and fight them off! ähnelt.
        /// </summary>
        internal static string THRESHOLD_DESCRIPTION {
            get {
                return ResourceManager.GetString("THRESHOLD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wolf ähnelt.
        /// </summary>
        internal static string WOLF {
            get {
                return ResourceManager.GetString("WOLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wyvern ähnelt.
        /// </summary>
        internal static string WYVERN {
            get {
                return ResourceManager.GetString("WYVERN", resourceCulture);
            }
        }
    }
}
