//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MobNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobNames() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.MobNames", typeof(MobNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Air Elemental ähnelt.
        /// </summary>
        internal static string AirElemental {
            get {
                return ResourceManager.GetString("AirElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aggressive Ape ähnelt.
        /// </summary>
        internal static string Ape {
            get {
                return ResourceManager.GetString("Ape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ash Elemental ähnelt.
        /// </summary>
        internal static string AshElemental {
            get {
                return ResourceManager.GetString("AshElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Huge Bat ähnelt.
        /// </summary>
        internal static string Bat {
            get {
                return ResourceManager.GetString("Bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bear ähnelt.
        /// </summary>
        internal static string BEAR {
            get {
                return ResourceManager.GetString("BEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anathema ähnelt.
        /// </summary>
        internal static string BlueSlaad {
            get {
                return ResourceManager.GetString("BlueSlaad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wild Boar ähnelt.
        /// </summary>
        internal static string BOAR {
            get {
                return ResourceManager.GetString("BOAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grand Wizard of the Order ähnelt.
        /// </summary>
        internal static string BOSS_CULTLEADER {
            get {
                return ResourceManager.GetString("BOSS_CULTLEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demonic Avatar ähnelt.
        /// </summary>
        internal static string BOSS_FINAL_DEMON {
            get {
                return ResourceManager.GetString("BOSS_FINAL_DEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ghostly Cultleader ähnelt.
        /// </summary>
        internal static string BOSS_GHOSTCULTLEADER {
            get {
                return ResourceManager.GetString("BOSS_GHOSTCULTLEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cloud Giant ähnelt.
        /// </summary>
        internal static string BOSS_GIANT {
            get {
                return ResourceManager.GetString("BOSS_GIANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant Rat ähnelt.
        /// </summary>
        internal static string BOSS_GIANTRAT {
            get {
                return ResourceManager.GetString("BOSS_GIANTRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Mover of Pieces ähnelt.
        /// </summary>
        internal static string BOSS_HEINRICH {
            get {
                return ResourceManager.GetString("BOSS_HEINRICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crushing Leviathan ähnelt.
        /// </summary>
        internal static string BOSS_LEVIATHAN {
            get {
                return ResourceManager.GetString("BOSS_LEVIATHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Centurion ähnelt.
        /// </summary>
        internal static string BOSS_MERCENARY {
            get {
                return ResourceManager.GetString("BOSS_MERCENARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grotesque Monstrosity ähnelt.
        /// </summary>
        internal static string BOSS_MONSTROSITY {
            get {
                return ResourceManager.GetString("BOSS_MONSTROSITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Necromancer ähnelt.
        /// </summary>
        internal static string BOSS_NECROMANCER {
            get {
                return ResourceManager.GetString("BOSS_NECROMANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Observer ähnelt.
        /// </summary>
        internal static string BOSS_OBSERVER {
            get {
                return ResourceManager.GetString("BOSS_OBSERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Uber Hunter ähnelt.
        /// </summary>
        internal static string BOSS_RENKE {
            get {
                return ResourceManager.GetString("BOSS_RENKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Archmagister ähnelt.
        /// </summary>
        internal static string BOSS_SOREN {
            get {
                return ResourceManager.GetString("BOSS_SOREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lich Lord ähnelt.
        /// </summary>
        internal static string BOSS_UBERNECRO {
            get {
                return ResourceManager.GetString("BOSS_UBERNECRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priest of the Void ähnelt.
        /// </summary>
        internal static string BOSS_VOIDPRIEST {
            get {
                return ResourceManager.GetString("BOSS_VOIDPRIEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buffalo ähnelt.
        /// </summary>
        internal static string Buffalo {
            get {
                return ResourceManager.GetString("Buffalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cockatrice ähnelt.
        /// </summary>
        internal static string Cockatrice {
            get {
                return ResourceManager.GetString("Cockatrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant Crab ähnelt.
        /// </summary>
        internal static string Crab {
            get {
                return ResourceManager.GetString("Crab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direwolf ähnelt.
        /// </summary>
        internal static string Direwolf {
            get {
                return ResourceManager.GetString("Direwolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Djinn ähnelt.
        /// </summary>
        internal static string Djinn {
            get {
                return ResourceManager.GetString("Djinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dragon ähnelt.
        /// </summary>
        internal static string DRAGON {
            get {
                return ResourceManager.GetString("DRAGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big Dragon ähnelt.
        /// </summary>
        internal static string DRAGON2 {
            get {
                return ResourceManager.GetString("DRAGON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bigger Dragon ähnelt.
        /// </summary>
        internal static string DRAGON3 {
            get {
                return ResourceManager.GetString("DRAGON3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Dummy ähnelt.
        /// </summary>
        internal static string DUMMY {
            get {
                return ResourceManager.GetString("DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Earth Elemental ähnelt.
        /// </summary>
        internal static string EarthElemental {
            get {
                return ResourceManager.GetString("EarthElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elephant ähnelt.
        /// </summary>
        internal static string Elephant {
            get {
                return ResourceManager.GetString("Elephant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fire Elemental ähnelt.
        /// </summary>
        internal static string FireElemental {
            get {
                return ResourceManager.GetString("FireElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest Troll ähnelt.
        /// </summary>
        internal static string ForestTroll {
            get {
                return ResourceManager.GetString("ForestTroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gargantuan Brute ähnelt.
        /// </summary>
        internal static string Gargantuan {
            get {
                return ResourceManager.GetString("Gargantuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gravecrawler ähnelt.
        /// </summary>
        internal static string Gravecrawler {
            get {
                return ResourceManager.GetString("Gravecrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Corpse Hound ähnelt.
        /// </summary>
        internal static string GraveHound {
            get {
                return ResourceManager.GetString("GraveHound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Harpy ähnelt.
        /// </summary>
        internal static string Harpy {
            get {
                return ResourceManager.GetString("Harpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hill Giant ähnelt.
        /// </summary>
        internal static string HillGiant {
            get {
                return ResourceManager.GetString("HillGiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hyena ähnelt.
        /// </summary>
        internal static string Hyena {
            get {
                return ResourceManager.GetString("Hyena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ice Elemental ähnelt.
        /// </summary>
        internal static string IceElemental {
            get {
                return ResourceManager.GetString("IceElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iron Elemental ähnelt.
        /// </summary>
        internal static string IronElemental {
            get {
                return ResourceManager.GetString("IronElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manticore ähnelt.
        /// </summary>
        internal static string Manticore {
            get {
                return ResourceManager.GetString("Manticore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goblin Knight ähnelt.
        /// </summary>
        internal static string MOB_1_CAV {
            get {
                return ResourceManager.GetString("MOB_1-CAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizard Swordman ähnelt.
        /// </summary>
        internal static string MOB_1_INF {
            get {
                return ResourceManager.GetString("MOB_1-INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventive&apos; Cannoneer ähnelt.
        /// </summary>
        internal static string MOB_2_ART {
            get {
                return ResourceManager.GetString("MOB_2-ART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blessed Cavalryman ähnelt.
        /// </summary>
        internal static string MOB_2_CAV {
            get {
                return ResourceManager.GetString("MOB_2-CAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feline Rifleman ähnelt.
        /// </summary>
        internal static string MOB_2_INF {
            get {
                return ResourceManager.GetString("MOB_2-INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flying Illusionist ähnelt.
        /// </summary>
        internal static string MOB_3_AIR {
            get {
                return ResourceManager.GetString("MOB_3-AIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Omari Rocket ähnelt.
        /// </summary>
        internal static string MOB_3_ART {
            get {
                return ResourceManager.GetString("MOB_3-ART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Psychic Tank ähnelt.
        /// </summary>
        internal static string MOB_3_CAV {
            get {
                return ResourceManager.GetString("MOB_3-CAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modern Infantry Monk ähnelt.
        /// </summary>
        internal static string MOB_3_INF {
            get {
                return ResourceManager.GetString("MOB_3-INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mole Warrior ähnelt.
        /// </summary>
        internal static string MOB_A_INF {
            get {
                return ResourceManager.GetString("MOB_A-INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abomination ähnelt.
        /// </summary>
        internal static string MOB_ABOMINATION {
            get {
                return ResourceManager.GetString("MOB_ABOMINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Machine ähnelt.
        /// </summary>
        internal static string MOB_ANCIENTMACHINE {
            get {
                return ResourceManager.GetString("MOB_ANCIENTMACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angry Chicken ähnelt.
        /// </summary>
        internal static string MOB_ANGRYCHICKEN {
            get {
                return ResourceManager.GetString("MOB_ANGRYCHICKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assassin ähnelt.
        /// </summary>
        internal static string MOB_ASSASSIN {
            get {
                return ResourceManager.GetString("MOB_ASSASSIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bigger Imp ähnelt.
        /// </summary>
        internal static string MOB_BIGGERIMP {
            get {
                return ResourceManager.GetString("MOB_BIGGERIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Big Rat ähnelt.
        /// </summary>
        internal static string MOB_BIGRAT {
            get {
                return ResourceManager.GetString("MOB_BIGRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Consuming Ooze ähnelt.
        /// </summary>
        internal static string MOB_CONSUMINGOOZE {
            get {
                return ResourceManager.GetString("MOB_CONSUMINGOOZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cultist ähnelt.
        /// </summary>
        internal static string MOB_CULTIST {
            get {
                return ResourceManager.GetString("MOB_CULTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knight of the Order ähnelt.
        /// </summary>
        internal static string MOB_CULTKNIGHT {
            get {
                return ResourceManager.GetString("MOB_CULTKNIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep One ähnelt.
        /// </summary>
        internal static string MOB_DEEPONE {
            get {
                return ResourceManager.GetString("MOB_DEEPONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Deep One ähnelt.
        /// </summary>
        internal static string MOB_DEEPONE2 {
            get {
                return ResourceManager.GetString("MOB_DEEPONE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scout from Beyond ähnelt.
        /// </summary>
        internal static string MOB_DEMONSCOUT {
            get {
                return ResourceManager.GetString("MOB_DEMONSCOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fanatic ähnelt.
        /// </summary>
        internal static string MOB_FANATIC {
            get {
                return ResourceManager.GetString("MOB_FANATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep Void Flamethrower ähnelt.
        /// </summary>
        internal static string MOB_FLAMETHROWER {
            get {
                return ResourceManager.GetString("MOB_FLAMETHROWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glimpse of Foes Ahead ähnelt.
        /// </summary>
        internal static string MOB_GLIMPSEA {
            get {
                return ResourceManager.GetString("MOB_GLIMPSEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glimpse of Foes Ahead ähnelt.
        /// </summary>
        internal static string MOB_GLIMPSEB {
            get {
                return ResourceManager.GetString("MOB_GLIMPSEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glimpse of Foes Ahead ähnelt.
        /// </summary>
        internal static string MOB_GLIMPSEC {
            get {
                return ResourceManager.GetString("MOB_GLIMPSEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pale Gorgon ähnelt.
        /// </summary>
        internal static string MOB_GORGON {
            get {
                return ResourceManager.GetString("MOB_GORGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greater Demon of the Void ähnelt.
        /// </summary>
        internal static string MOB_GREATERDEMON {
            get {
                return ResourceManager.GetString("MOB_GREATERDEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Majestic Lion ähnelt.
        /// </summary>
        internal static string MOB_GRYPHON {
            get {
                return ResourceManager.GetString("MOB_GRYPHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep Void Imp ähnelt.
        /// </summary>
        internal static string MOB_HORNEDIMP {
            get {
                return ResourceManager.GetString("MOB_HORNEDIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angry Badger ähnelt.
        /// </summary>
        internal static string MOB_HUFFLE {
            get {
                return ResourceManager.GetString("MOB_HUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hydramarine ähnelt.
        /// </summary>
        internal static string MOB_HYDRAMARINE {
            get {
                return ResourceManager.GetString("MOB_HYDRAMARINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imp ähnelt.
        /// </summary>
        internal static string MOB_IMP {
            get {
                return ResourceManager.GetString("MOB_IMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imp Warlock ähnelt.
        /// </summary>
        internal static string MOB_IMPWARLOCK {
            get {
                return ResourceManager.GetString("MOB_IMPWARLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spikeback Juggernaut ähnelt.
        /// </summary>
        internal static string MOB_JUGGERNAUT {
            get {
                return ResourceManager.GetString("MOB_JUGGERNAUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lesser Demon of the Void ähnelt.
        /// </summary>
        internal static string MOB_LESSERDEMON {
            get {
                return ResourceManager.GetString("MOB_LESSERDEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Space Warrior ähnelt.
        /// </summary>
        internal static string MOB_MARINE {
            get {
                return ResourceManager.GetString("MOB_MARINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Martial Artist ähnelt.
        /// </summary>
        internal static string MOB_MARTIALARTIST {
            get {
                return ResourceManager.GetString("MOB_MARTIALARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Legionnaire ähnelt.
        /// </summary>
        internal static string MOB_MERCENARY {
            get {
                return ResourceManager.GetString("MOB_MERCENARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Legionnaire ähnelt.
        /// </summary>
        internal static string MOB_MERCENARY2 {
            get {
                return ResourceManager.GetString("MOB_MERCENARY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automaton Guardian ähnelt.
        /// </summary>
        internal static string MOB_OVERSOUL {
            get {
                return ResourceManager.GetString("MOB_OVERSOUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sewerghost ähnelt.
        /// </summary>
        internal static string MOB_POISONGHOST {
            get {
                return ResourceManager.GetString("MOB_POISONGHOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rat ähnelt.
        /// </summary>
        internal static string MOB_RAT {
            get {
                return ResourceManager.GetString("MOB_RAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spooky Raven ähnelt.
        /// </summary>
        internal static string MOB_RAVEN {
            get {
                return ResourceManager.GetString("MOB_RAVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secret Entrance ähnelt.
        /// </summary>
        internal static string MOB_SECRETGATE {
            get {
                return ResourceManager.GetString("MOB_SECRETGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fallen Seraph ähnelt.
        /// </summary>
        internal static string MOB_SERAPH {
            get {
                return ResourceManager.GetString("MOB_SERAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basilisk ähnelt.
        /// </summary>
        internal static string MOB_SEWERSNAKE {
            get {
                return ResourceManager.GetString("MOB_SEWERSNAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shadowbull ähnelt.
        /// </summary>
        internal static string MOB_SHADOWBULL {
            get {
                return ResourceManager.GetString("MOB_SHADOWBULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shark ähnelt.
        /// </summary>
        internal static string MOB_SHARK {
            get {
                return ResourceManager.GetString("MOB_SHARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skeleton ähnelt.
        /// </summary>
        internal static string MOB_SKELETON {
            get {
                return ResourceManager.GetString("MOB_SKELETON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imposing Serpent ähnelt.
        /// </summary>
        internal static string MOB_SNAKE {
            get {
                return ResourceManager.GetString("MOB_SNAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest Widow ähnelt.
        /// </summary>
        internal static string MOB_SPIDER {
            get {
                return ResourceManager.GetString("MOB_SPIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest Tarantula ähnelt.
        /// </summary>
        internal static string MOB_SPIDER2 {
            get {
                return ResourceManager.GetString("MOB_SPIDER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spikeback Marauder ähnelt.
        /// </summary>
        internal static string MOB_SPIKEDDEMON {
            get {
                return ResourceManager.GetString("MOB_SPIKEDDEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep Void Ram ähnelt.
        /// </summary>
        internal static string MOB_TAURUS {
            get {
                return ResourceManager.GetString("MOB_TAURUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terracotta Guard ähnelt.
        /// </summary>
        internal static string MOB_TERRACOTTA {
            get {
                return ResourceManager.GetString("MOB_TERRACOTTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terracotta General ähnelt.
        /// </summary>
        internal static string MOB_TERRACOTTA2 {
            get {
                return ResourceManager.GetString("MOB_TERRACOTTA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Three Headed Watchdog ähnelt.
        /// </summary>
        internal static string MOB_THREEHEADEDDOG {
            get {
                return ResourceManager.GetString("MOB_THREEHEADEDDOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lumbering Construct ähnelt.
        /// </summary>
        internal static string MOB_TRASH1 {
            get {
                return ResourceManager.GetString("MOB_TRASH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slinging Construct ähnelt.
        /// </summary>
        internal static string MOB_TRASH2 {
            get {
                return ResourceManager.GetString("MOB_TRASH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slithering Construct ähnelt.
        /// </summary>
        internal static string MOB_TRASH3 {
            get {
                return ResourceManager.GetString("MOB_TRASH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executioner Trio ähnelt.
        /// </summary>
        internal static string MOB_TRIO {
            get {
                return ResourceManager.GetString("MOB_TRIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vengeful Dummy ähnelt.
        /// </summary>
        internal static string MOB_VENGEFULDUMMY {
            get {
                return ResourceManager.GetString("MOB_VENGEFULDUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spikeback Crawler ähnelt.
        /// </summary>
        internal static string MOB_VOIDCRAWLER {
            get {
                return ResourceManager.GetString("MOB_VOIDCRAWLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Void Infused Cultist ähnelt.
        /// </summary>
        internal static string MOB_VOIDCULTIST {
            get {
                return ResourceManager.GetString("MOB_VOIDCULTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Void Fiend ähnelt.
        /// </summary>
        internal static string MOB_VOIDFIEND {
            get {
                return ResourceManager.GetString("MOB_VOIDFIEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warlock ähnelt.
        /// </summary>
        internal static string MOB_WARLOCK {
            get {
                return ResourceManager.GetString("MOB_WARLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wendigo ähnelt.
        /// </summary>
        internal static string MOB_WENDIGO {
            get {
                return ResourceManager.GetString("MOB_WENDIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aggressive Tree ähnelt.
        /// </summary>
        internal static string MOB_WILLOW {
            get {
                return ResourceManager.GetString("MOB_WILLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Winged Demon ähnelt.
        /// </summary>
        internal static string MOB_WINGEDDEMON {
            get {
                return ResourceManager.GetString("MOB_WINGEDDEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zombie ähnelt.
        /// </summary>
        internal static string MOB_ZOMBIE {
            get {
                return ResourceManager.GetString("MOB_ZOMBIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ogre ähnelt.
        /// </summary>
        internal static string OGRE {
            get {
                return ResourceManager.GetString("OGRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polarbear ähnelt.
        /// </summary>
        internal static string Polarbear {
            get {
                return ResourceManager.GetString("Polarbear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Porcupine ähnelt.
        /// </summary>
        internal static string Porcupine {
            get {
                return ResourceManager.GetString("Porcupine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant Scorpion ähnelt.
        /// </summary>
        internal static string Scorpion {
            get {
                return ResourceManager.GetString("Scorpion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shadow Giant ähnelt.
        /// </summary>
        internal static string ShadowGiant {
            get {
                return ResourceManager.GetString("ShadowGiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sphinx Hound ähnelt.
        /// </summary>
        internal static string SphinxHound {
            get {
                return ResourceManager.GetString("SphinxHound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swamp Troll ähnelt.
        /// </summary>
        internal static string SwampTroll {
            get {
                return ResourceManager.GetString("SwampTroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Treant ähnelt.
        /// </summary>
        internal static string Treant {
            get {
                return ResourceManager.GetString("Treant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umber Hulk ähnelt.
        /// </summary>
        internal static string UmberHulk {
            get {
                return ResourceManager.GetString("UmberHulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Water Elemental ähnelt.
        /// </summary>
        internal static string WaterElemental {
            get {
                return ResourceManager.GetString("WaterElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Werebull ähnelt.
        /// </summary>
        internal static string Werebull {
            get {
                return ResourceManager.GetString("Werebull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Child of Ornlu ähnelt.
        /// </summary>
        internal static string Werewolf {
            get {
                return ResourceManager.GetString("Werewolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wolf ähnelt.
        /// </summary>
        internal static string WOLF {
            get {
                return ResourceManager.GetString("WOLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wood Elemental ähnelt.
        /// </summary>
        internal static string WoodElemental {
            get {
                return ResourceManager.GetString("WoodElemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wyvern ähnelt.
        /// </summary>
        internal static string WYVERN {
            get {
                return ResourceManager.GetString("WYVERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yeti ähnelt.
        /// </summary>
        internal static string Yeti {
            get {
                return ResourceManager.GetString("Yeti", resourceCulture);
            }
        }
    }
}
