//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Places {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Places() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.Places", typeof(Places).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Crypt ähnelt.
        /// </summary>
        internal static string Dungeon_Crypt {
            get {
                return ResourceManager.GetString("Dungeon_Crypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is something stirring beneath the graveyard...
        ///
        ///This dungeon awards armor pieces ähnelt.
        /// </summary>
        internal static string Dungeon_Crypt_Description {
            get {
                return ResourceManager.GetString("Dungeon_Crypt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cult&apos;s Stronghold ähnelt.
        /// </summary>
        internal static string Dungeon_CultistCastle {
            get {
                return ResourceManager.GetString("Dungeon_CultistCastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The traiterous lord who had hired the mercenaries has turned his castle into the cult&apos;s base of operations. ähnelt.
        /// </summary>
        internal static string Dungeon_CultistCastle_Description {
            get {
                return ResourceManager.GetString("Dungeon_CultistCastle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Red Pagoda ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameDistant {
            get {
                return ResourceManager.GetString("Dungeon_EndgameDistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameDistant_Description {
            get {
                return ResourceManager.GetString("Dungeon_EndgameDistant_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wizard Academy ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameMagic {
            get {
                return ResourceManager.GetString("Dungeon_EndgameMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameMagic_Description {
            get {
                return ResourceManager.GetString("Dungeon_EndgameMagic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Sunken City ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameTechnology {
            get {
                return ResourceManager.GetString("Dungeon_EndgameTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There&apos;s a forgotten city in a deep trench in the bottom of the sea... ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameTechnology_Description {
            get {
                return ResourceManager.GetString("Dungeon_EndgameTechnology_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Labyrinth ähnelt.
        /// </summary>
        internal static string Dungeon_Labyrinth {
            get {
                return ResourceManager.GetString("Dungeon_Labyrinth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Below the castle, there is a huge, labyrinthian dungeon. This must be where the leader of the cult is hiding. ähnelt.
        /// </summary>
        internal static string Dungeon_Labyrinth_Description {
            get {
                return ResourceManager.GetString("Dungeon_Labyrinth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Beacon ähnelt.
        /// </summary>
        internal static string Dungeon_Lighthouse {
            get {
                return ResourceManager.GetString("Dungeon_Lighthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cultists have holed up near the old beacon. The blue flames they lit have attracted more than just ships. ähnelt.
        /// </summary>
        internal static string Dungeon_Lighthouse_Description {
            get {
                return ResourceManager.GetString("Dungeon_Lighthouse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Camp ähnelt.
        /// </summary>
        internal static string Dungeon_MercenaryCamp {
            get {
                return ResourceManager.GetString("Dungeon_MercenaryCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cultists have acquired the services of a company of human mercenaries. Raiding their camp and killing their leader should drive them away. ähnelt.
        /// </summary>
        internal static string Dungeon_MercenaryCamp_Description {
            get {
                return ResourceManager.GetString("Dungeon_MercenaryCamp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Den of Rats ähnelt.
        /// </summary>
        internal static string Dungeon_RatDen {
            get {
                return ResourceManager.GetString("Dungeon_RatDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighting rats, clearing some kind of den... A good start to a glorious adventure.
        ///
        ///This dungeon awards weapons ähnelt.
        /// </summary>
        internal static string Dungeon_RatDen_Description {
            get {
                return ResourceManager.GetString("Dungeon_RatDen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Lighthouse ähnelt.
        /// </summary>
        internal static string Dungeon_ReturnToLighthouse {
            get {
                return ResourceManager.GetString("Dungeon_ReturnToLighthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While you were fighting in the cultist leader&apos;s castle, he and his followers have hurried to the old lighthouse to complete the ritual. ähnelt.
        /// </summary>
        internal static string Dungeon_ReturnToLighthouse_Description {
            get {
                return ResourceManager.GetString("Dungeon_ReturnToLighthouse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Temple ähnelt.
        /// </summary>
        internal static string Dungeon_Temple {
            get {
                return ResourceManager.GetString("Dungeon_Temple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cultists have relocated to the catacombs below the ruins of an ancient elven temple. ähnelt.
        /// </summary>
        internal static string Dungeon_Temple_Description {
            get {
                return ResourceManager.GetString("Dungeon_Temple_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Threshold ähnelt.
        /// </summary>
        internal static string Dungeon_Threshold {
            get {
                return ResourceManager.GetString("Dungeon_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We were too late! The ritual has been completed and the gate between the dimensions has been opened. An army of demons is flooding through the rift. Stand fast and fight them off! ähnelt.
        /// </summary>
        internal static string Dungeon_Threshold_Description {
            get {
                return ResourceManager.GetString("Dungeon_Threshold_Description", resourceCulture);
            }
        }
    }
}
