//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Places {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Places() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.Places", typeof(Places).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Crypt ähnelt.
        /// </summary>
        internal static string Dungeon_Crypt {
            get {
                return ResourceManager.GetString("Dungeon_Crypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cult&apos;s Stronghold ähnelt.
        /// </summary>
        internal static string Dungeon_CultistCastle {
            get {
                return ResourceManager.GetString("Dungeon_CultistCastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Red Pagoda ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameDistant {
            get {
                return ResourceManager.GetString("Dungeon_EndgameDistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wizard Academy ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameMagic {
            get {
                return ResourceManager.GetString("Dungeon_EndgameMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Sunken City ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameTechnology {
            get {
                return ResourceManager.GetString("Dungeon_EndgameTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Labyrinth ähnelt.
        /// </summary>
        internal static string Dungeon_Labyrinth {
            get {
                return ResourceManager.GetString("Dungeon_Labyrinth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Lighthouse ähnelt.
        /// </summary>
        internal static string Dungeon_Lighthouse {
            get {
                return ResourceManager.GetString("Dungeon_Lighthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Camp ähnelt.
        /// </summary>
        internal static string Dungeon_MercenaryCamp {
            get {
                return ResourceManager.GetString("Dungeon_MercenaryCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Den of Rats ähnelt.
        /// </summary>
        internal static string Dungeon_RatDen {
            get {
                return ResourceManager.GetString("Dungeon_RatDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Lighthouse II ähnelt.
        /// </summary>
        internal static string Dungeon_ReturnToLighthouse {
            get {
                return ResourceManager.GetString("Dungeon_ReturnToLighthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Temple ähnelt.
        /// </summary>
        internal static string Dungeon_Temple {
            get {
                return ResourceManager.GetString("Dungeon_Temple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Threshold ähnelt.
        /// </summary>
        internal static string Dungeon_Threshold {
            get {
                return ResourceManager.GetString("Dungeon_Threshold", resourceCulture);
            }
        }
    }
}
