//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Places {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Places() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.Places", typeof(Places).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Void Pathway 1 ähnelt.
        /// </summary>
        internal static string Dng_Void_Floor0 {
            get {
                return ResourceManager.GetString("Dng_Void_Floor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Void Pathway 2 ähnelt.
        /// </summary>
        internal static string Dng_Void_Floor1 {
            get {
                return ResourceManager.GetString("Dng_Void_Floor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guard Post ähnelt.
        /// </summary>
        internal static string Dng_Void_Floor2 {
            get {
                return ResourceManager.GetString("Dng_Void_Floor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep Void 1 ähnelt.
        /// </summary>
        internal static string Dng_Void_Floor3 {
            get {
                return ResourceManager.GetString("Dng_Void_Floor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep Void 2 ähnelt.
        /// </summary>
        internal static string Dng_Void_Floor4 {
            get {
                return ResourceManager.GetString("Dng_Void_Floor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deep Void Fortress ähnelt.
        /// </summary>
        internal static string Dng_Void_Floor5 {
            get {
                return ResourceManager.GetString("Dng_Void_Floor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crypt ähnelt.
        /// </summary>
        internal static string Dungeon_Crypt {
            get {
                return ResourceManager.GetString("Dungeon_Crypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is something stirring beneath the graveyard...
        ///
        ///This dungeon awards armor pieces ähnelt.
        /// </summary>
        internal static string Dungeon_Crypt_Description {
            get {
                return ResourceManager.GetString("Dungeon_Crypt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cult&apos;s Stronghold ähnelt.
        /// </summary>
        internal static string Dungeon_CultistCastle {
            get {
                return ResourceManager.GetString("Dungeon_CultistCastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The traiterous lord who had hired the mercenaries has turned his castle into the cult&apos;s base of operations. ähnelt.
        /// </summary>
        internal static string Dungeon_CultistCastle_Description {
            get {
                return ResourceManager.GetString("Dungeon_CultistCastle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Palace of Ages ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameAges {
            get {
                return ResourceManager.GetString("Dungeon_EndgameAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In this place, the past and the future are one and the same. It was and will be constructed by the leaders of many civilizations among the mystical terrains of the far plains. ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameAges_Description {
            get {
                return ResourceManager.GetString("Dungeon_EndgameAges_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Red Pagoda ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameDistant {
            get {
                return ResourceManager.GetString("Dungeon_EndgameDistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Atop a distant mountain, the Red Pagoda is overlooking the clouds and the lands below. ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameDistant_Description {
            get {
                return ResourceManager.GetString("Dungeon_EndgameDistant_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wizard Academy ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameMagic {
            get {
                return ResourceManager.GetString("Dungeon_EndgameMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This magical place is hidden away in the remote highlands. Here, the most promising young apprentices were educated in the art of magic. ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameMagic_Description {
            get {
                return ResourceManager.GetString("Dungeon_EndgameMagic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Banished Pyramid ähnelt.
        /// </summary>
        internal static string Dungeon_EndgamePyramid {
            get {
                return ResourceManager.GetString("Dungeon_EndgamePyramid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glowing portals lead to the entrance of this monument. It was built by an ancient race that has since been exiled from this world. ähnelt.
        /// </summary>
        internal static string Dungeon_EndgamePyramid_Description {
            get {
                return ResourceManager.GetString("Dungeon_EndgamePyramid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Sunken City ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameTechnology {
            get {
                return ResourceManager.GetString("Dungeon_EndgameTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There&apos;s a forgotten city in a deep trench in the bottom of the sea... ähnelt.
        /// </summary>
        internal static string Dungeon_EndgameTechnology_Description {
            get {
                return ResourceManager.GetString("Dungeon_EndgameTechnology_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Labyrinth ähnelt.
        /// </summary>
        internal static string Dungeon_Labyrinth {
            get {
                return ResourceManager.GetString("Dungeon_Labyrinth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Below the castle, there is a huge, labyrinthine dungeon. This must be where the leader of the cult is hiding. ähnelt.
        /// </summary>
        internal static string Dungeon_Labyrinth_Description {
            get {
                return ResourceManager.GetString("Dungeon_Labyrinth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beacon ähnelt.
        /// </summary>
        internal static string Dungeon_Lighthouse {
            get {
                return ResourceManager.GetString("Dungeon_Lighthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cultists have made their base at this beacon to prepare their ritual. ähnelt.
        /// </summary>
        internal static string Dungeon_Lighthouse_Description {
            get {
                return ResourceManager.GetString("Dungeon_Lighthouse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mercenary Camp ähnelt.
        /// </summary>
        internal static string Dungeon_MercenaryCamp {
            get {
                return ResourceManager.GetString("Dungeon_MercenaryCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cultists have acquired the services of a company of human mercenaries. Raiding their camp and killing their leader should drive them away. ähnelt.
        /// </summary>
        internal static string Dungeon_MercenaryCamp_Description {
            get {
                return ResourceManager.GetString("Dungeon_MercenaryCamp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Den of Rats ähnelt.
        /// </summary>
        internal static string Dungeon_RatDen {
            get {
                return ResourceManager.GetString("Dungeon_RatDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighting rats, clearing some kind of den... A good start to a glorious adventure.
        ///
        ///This dungeon awards weapons ähnelt.
        /// </summary>
        internal static string Dungeon_RatDen_Description {
            get {
                return ResourceManager.GetString("Dungeon_RatDen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lighthouse ähnelt.
        /// </summary>
        internal static string Dungeon_ReturnToLighthouse {
            get {
                return ResourceManager.GetString("Dungeon_ReturnToLighthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This ancient lighthouse is the nexus of the cult&apos;s final ritual. ähnelt.
        /// </summary>
        internal static string Dungeon_ReturnToLighthouse_Description {
            get {
                return ResourceManager.GetString("Dungeon_ReturnToLighthouse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ancient Temple ähnelt.
        /// </summary>
        internal static string Dungeon_Temple {
            get {
                return ResourceManager.GetString("Dungeon_Temple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cultists have relocated to the catacombs below the ruins of an ancient elven temple. ähnelt.
        /// </summary>
        internal static string Dungeon_Temple_Description {
            get {
                return ResourceManager.GetString("Dungeon_Temple_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Threshold ähnelt.
        /// </summary>
        internal static string Dungeon_Threshold {
            get {
                return ResourceManager.GetString("Dungeon_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ritual has been completed and the gate between the dimensions has been opened. An army of demons is flooding through the rift. Stand fast and fight them off! ähnelt.
        /// </summary>
        internal static string Dungeon_Threshold_Description {
            get {
                return ResourceManager.GetString("Dungeon_Threshold_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Void ähnelt.
        /// </summary>
        internal static string Dungeon_Void {
            get {
                return ResourceManager.GetString("Dungeon_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A sprawling web of pathways exists beyond the threshold. Incredible adventures await those who dare to explore them. ähnelt.
        /// </summary>
        internal static string Dungeon_Void_Description {
            get {
                return ResourceManager.GetString("Dungeon_Void_Description", resourceCulture);
            }
        }
    }
}
