//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Quests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Quests() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.Quests", typeof(Quests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From humble beginnings, battling dummies and rats, to defending your world against an invasion, to walking between worlds yourself - you’ve come so far. Each challenge demanded not just strength but also your craftiness and dedication. You honed your skills, forged your path (and your gear), and became the hero these trials required.
        ///For now, your story ends here. But who knows? In realms like these, endings often make way for new beginnings. ähnelt.
        /// </summary>
        internal static string Endgame_Finished {
            get {
                return ResourceManager.GetString("Endgame_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your expeditions into the Void have been many. Time and again, you’ve braved its twisting paths and shadowed expanses, pushing further with each foray.
        ///Now, the twisting pathways converge and you find yourself in front of three portals, their flickering light unmistakably similar to the one you have been using to travel between this world and your own. These must be the remnants of other severed connections, doorways that survived the collapse.
        ///Beyond them, your ultimate challenge awaits you. ähnelt.
        /// </summary>
        internal static string Endgame_Pinnacle {
            get {
                return ResourceManager.GetString("Endgame_Pinnacle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The landscape around the lighthouse snaps into focus. You stagger as the world feels both immediate and distant, like waking from a dream. You remember fighting at the threshold, then just a moment of indescribable nothingness.
        ///The sharp voices of those around you cut through the haze. The survivors stare, their astonishment giving way to joy. They rush toward you, some shouting your name. They say you vanished for mere seconds, yet the void clings faintly to your thoughts, a sensation without form. ähnelt.
        /// </summary>
        internal static string Endgame_Start {
            get {
                return ResourceManager.GetString("Endgame_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The portal’s connection is severed but the rupture in reality persists. What once served as a bridge to another place now stands adrift, its energy still surging but its destination lost.
        ///Through the bluish glow, an unfamiliar realm comes into view. A web of twisting pathways stretches into the void, branching endlessly into a shadowed expanse. A landscape as intriguing as it is unsettling.
        ///The void beckons to the bold and the reckless, a realm of mysteries that promise both great reward and untold peril. ähnelt.
        /// </summary>
        internal static string Endgame_Void {
            get {
                return ResourceManager.GetString("Endgame_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Story_CastleFinished {
            get {
                return ResourceManager.GetString("Story_CastleFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The time has come to confront the treacherous lord who commands the cult threatening the realm. Within the walls of this castle you hope to find their secret headquarter. Here, you might be able to put an end to their insidious activities once and for all. ähnelt.
        /// </summary>
        internal static string Story_CastleOpen {
            get {
                return ResourceManager.GetString("Story_CastleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You stand victorious in the corridors beneath the cultists&apos; castle. While the leader himself has eluded you, destroying their final hideout should spell the end of the cult’s sinister activities.
        ///
        ///But your optimism wanes as you realize that his escape wasn&apos;t a defeat but a strategic retreat: Several documents and maps identify an ancient lighthouse that sits atop a nearby cliff as the locus of a final ritual which will break down the walls between worlds. You need to pursue the remaining cultists and prev [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Story_LabyrinthFinished {
            get {
                return ResourceManager.GetString("Story_LabyrinthFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beneath the castle, there is a giant labyrinthine dungeon. The cult&apos;s inner sanctum has to be in there. ähnelt.
        /// </summary>
        internal static string Story_LabyrinthOpen {
            get {
                return ResourceManager.GetString("Story_LabyrinthOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You confront the last of the cultists and their otherworldly allies, illuminated by the ghastly blue fire that burns atop the lighthouse. Suddenly, a surge of energy courses through the building, causing the azure flames to leap higher. There is a blinding flash, as the lighthouse&apos;s beams pierce the veil between worlds, burning the fabric of reality itself and creating a monstrous portal to the abyss beyond. ähnelt.
        /// </summary>
        internal static string Story_Lighthouse2Finished {
            get {
                return ResourceManager.GetString("Story_Lighthouse2Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die As you approach the lighthouse, you do not have to ask yourself if the ritual has already started: Each step on the rocky ground resonates with a discordant energy, and the very fabric of the world seems to ripple and warp around you. Shadows, thrown by the setting sun, appear twisted into grotesque shapes, and the air is pulsing with an otherworldly hum. You need to put an end to this, before the last boundaries between the worlds are dissolved. ähnelt.
        /// </summary>
        internal static string Story_Lighthouse2Open {
            get {
                return ResourceManager.GetString("Story_Lighthouse2Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The beacon&apos;s blue beam seems to have attracted the attention of more than just ships. The cultists have somehow opened a gateway to a different world. Fortunately, disturbing their ritual caused the gate to collapse before too many of the demonic beasts could make it through.
        ///You need to keep an eye out for further activities of these cultists! ähnelt.
        /// </summary>
        internal static string Story_LighthouseFinished {
            get {
                return ResourceManager.GetString("Story_LighthouseFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have found the old beacon near which the cultists have made their camp. It is not exactly hard to spot, given that its beam is lit by a strange blue flame. ähnelt.
        /// </summary>
        internal static string Story_LighthouseOpen {
            get {
                return ResourceManager.GetString("Story_LighthouseOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are rumours that a sinister cult of demon worshippers is operating in the area. You should look into that. ähnelt.
        /// </summary>
        internal static string Story_QuestReceived {
            get {
                return ResourceManager.GetString("Story_QuestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After driving away its inhabitants, you search their hideout for clues to their further activities and make a huge discovery: It appears that the head of the cult is a powerful lord from a neighbouring region. You have to continue your journey to his castle and confront him. ähnelt.
        /// </summary>
        internal static string Story_TempleFinished {
            get {
                return ResourceManager.GetString("Story_TempleFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The cultists have established another hideout inside an ancient elvish temple. You need to drive them out before they manage to start another demonic incursion. ähnelt.
        /// </summary>
        internal static string Story_TempleOpen {
            get {
                return ResourceManager.GetString("Story_TempleOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At the threshold between worlds you encounter the demonic champion. As you clash, time and space appear to to twist around you until everything just... stops. ähnelt.
        /// </summary>
        internal static string Story_ThresholdFinished {
            get {
                return ResourceManager.GetString("Story_ThresholdFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The portal to the demonic realm stands wide open, a mesmerizing yet terrifying spectacle. A once-controllable situation has spiraled into an existential crisis, and now, a malevolent army spills forth. You cannot know how long this gateway will remain open or if it will ever close again. All you can do now, is to guard the threshold against the encroaching darkness and drive back whatever foe attempts to cross it. ähnelt.
        /// </summary>
        internal static string Story_ThresholdOpen {
            get {
                return ResourceManager.GetString("Story_ThresholdOpen", resourceCulture);
            }
        }
    }
}
