//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Skills {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skills() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.Skills", typeof(Skills).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imbue your weapon with the fiery energy. Grants a percentage of the weapons damage as extra base fire damage. ähnelt.
        /// </summary>
        internal static string BlazingWeapon_Description {
            get {
                return ResourceManager.GetString("BlazingWeapon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blazing Weapon ähnelt.
        /// </summary>
        internal static string BlazingWeapon_Name {
            get {
                return ResourceManager.GetString("BlazingWeapon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase the effect duration of Blazing Weapon ähnelt.
        /// </summary>
        internal static string BlazingWeaponSupport_Description {
            get {
                return ResourceManager.GetString("BlazingWeaponSupport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lasting Flame ähnelt.
        /// </summary>
        internal static string BlazingWeaponSupport_Name {
            get {
                return ResourceManager.GetString("BlazingWeaponSupport_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dual Wielding ähnelt.
        /// </summary>
        internal static string DualWield1 {
            get {
                return ResourceManager.GetString("DualWield1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coat your weapon in a powerful toxin to deal additional base damage as poison with every hit ähnelt.
        /// </summary>
        internal static string EnvWeapon_Description {
            get {
                return ResourceManager.GetString("EnvWeapon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Envenom Weapon ähnelt.
        /// </summary>
        internal static string EnvWeapon_Name {
            get {
                return ResourceManager.GetString("EnvWeapon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase execution speed and cooldown recovery of the Envenom Weapon Skill ähnelt.
        /// </summary>
        internal static string EnvWeaponSupport_Description {
            get {
                return ResourceManager.GetString("EnvWeaponSupport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Efficient Application ähnelt.
        /// </summary>
        internal static string EnvWeaponSupport_Name {
            get {
                return ResourceManager.GetString("EnvWeaponSupport_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path of the Fighter ähnelt.
        /// </summary>
        internal static string PathFighter {
            get {
                return ResourceManager.GetString("PathFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighter ähnelt.
        /// </summary>
        internal static string PathFighterRoot {
            get {
                return ResourceManager.GetString("PathFighterRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shieldbearer ähnelt.
        /// </summary>
        internal static string Shield1 {
            get {
                return ResourceManager.GetString("Shield1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fencer ähnelt.
        /// </summary>
        internal static string SingleHanded1 {
            get {
                return ResourceManager.GetString("SingleHanded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wide Swings ähnelt.
        /// </summary>
        internal static string TwoHanded1 {
            get {
                return ResourceManager.GetString("TwoHanded1", resourceCulture);
            }
        }
    }
}
