//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheIdleScrolls_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Skills {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skills() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheIdleScrolls_Core.Properties.Skills", typeof(Skills).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Higher levels have biffer effect and longer duration ähnelt.
        /// </summary>
        internal static string BattleCry_Description {
            get {
                return ResourceManager.GetString("BattleCry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battle Cry ähnelt.
        /// </summary>
        internal static string BattleCry_Name {
            get {
                return ResourceManager.GetString("BattleCry_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The inspiration from your Battle Cry makes you nearly unstoppable: Battle Cry also grants increased defense and stun resistance ähnelt.
        /// </summary>
        internal static string BattleCryBuff_Description {
            get {
                return ResourceManager.GetString("BattleCryBuff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inspiring Cry ähnelt.
        /// </summary>
        internal static string BattleCryBuff_Name {
            get {
                return ResourceManager.GetString("BattleCryBuff_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your intimidating Battle Cry applies a debuff to your opponents, hindering their ability to use skills and mitigate damage. ähnelt.
        /// </summary>
        internal static string BattleCryDebuff_Description {
            get {
                return ResourceManager.GetString("BattleCryDebuff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fearsome Cry ähnelt.
        /// </summary>
        internal static string BattleCryDebuff_Name {
            get {
                return ResourceManager.GetString("BattleCryDebuff_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imbue your weapon with the fiery energy. Grants a percentage of the weapons damage as extra base fire damage. ähnelt.
        /// </summary>
        internal static string BlazingWeapon_Description {
            get {
                return ResourceManager.GetString("BlazingWeapon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blazing Weapon ähnelt.
        /// </summary>
        internal static string BlazingWeapon_Name {
            get {
                return ResourceManager.GetString("BlazingWeapon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase the effect duration of the Blazing Weapon skill ähnelt.
        /// </summary>
        internal static string BlazingWeaponSupport_Description {
            get {
                return ResourceManager.GetString("BlazingWeaponSupport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lasting Flame ähnelt.
        /// </summary>
        internal static string BlazingWeaponSupport_Name {
            get {
                return ResourceManager.GetString("BlazingWeaponSupport_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string CrushingBlow_Description {
            get {
                return ResourceManager.GetString("CrushingBlow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crushing Blow ähnelt.
        /// </summary>
        internal static string CrushingBlow_Name {
            get {
                return ResourceManager.GetString("CrushingBlow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DoubleStrike_Description {
            get {
                return ResourceManager.GetString("DoubleStrike_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Double Strike ähnelt.
        /// </summary>
        internal static string DoubleStrike_Name {
            get {
                return ResourceManager.GetString("DoubleStrike_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two Weapons I ähnelt.
        /// </summary>
        internal static string DualWield1 {
            get {
                return ResourceManager.GetString("DualWield1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two Weapons II ähnelt.
        /// </summary>
        internal static string DualWield2 {
            get {
                return ResourceManager.GetString("DualWield2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two Weapons III ähnelt.
        /// </summary>
        internal static string DualWield3 {
            get {
                return ResourceManager.GetString("DualWield3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coat your weapon in a powerful toxin to deal additional base damage as poison with every hit ähnelt.
        /// </summary>
        internal static string EnvWeapon_Description {
            get {
                return ResourceManager.GetString("EnvWeapon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Envenom Weapon ähnelt.
        /// </summary>
        internal static string EnvWeapon_Name {
            get {
                return ResourceManager.GetString("EnvWeapon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase execution speed and cooldown recovery of the Envenom Weapon skill ähnelt.
        /// </summary>
        internal static string EnvWeaponSupport_Description {
            get {
                return ResourceManager.GetString("EnvWeaponSupport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Efficient Application ähnelt.
        /// </summary>
        internal static string EnvWeaponSupport_Name {
            get {
                return ResourceManager.GetString("EnvWeaponSupport_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string HeavyAttack_Description {
            get {
                return ResourceManager.GetString("HeavyAttack_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Heavy Attacks gain an extra damage multiplier for every time you have used your Default Attack this fight ähnelt.
        /// </summary>
        internal static string HeavyAttack_DualWield_Description {
            get {
                return ResourceManager.GetString("HeavyAttack_DualWield_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finishing Move ähnelt.
        /// </summary>
        internal static string HeavyAttack_DualWield_Name {
            get {
                return ResourceManager.GetString("HeavyAttack_DualWield_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Attack ähnelt.
        /// </summary>
        internal static string HeavyAttack_Name {
            get {
                return ResourceManager.GetString("HeavyAttack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage from Heavy Attacks is increased by your total armor rating ähnelt.
        /// </summary>
        internal static string HeavyAttack_Shielded_Description {
            get {
                return ResourceManager.GetString("HeavyAttack_Shielded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Best Offense... ähnelt.
        /// </summary>
        internal static string HeavyAttack_Shielded_Name {
            get {
                return ResourceManager.GetString("HeavyAttack_Shielded_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Heavy Attacks deal significantly increased damage to opponents that are on low life ähnelt.
        /// </summary>
        internal static string HeavyAttack_SingleHanded_Description {
            get {
                return ResourceManager.GetString("HeavyAttack_SingleHanded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Culling Strike ähnelt.
        /// </summary>
        internal static string HeavyAttack_SingleHanded_Name {
            get {
                return ResourceManager.GetString("HeavyAttack_SingleHanded_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Heavy Attacks cause stuns ähnelt.
        /// </summary>
        internal static string HeavyAttack_TwoHanded_Description {
            get {
                return ResourceManager.GetString("HeavyAttack_TwoHanded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smash! ähnelt.
        /// </summary>
        internal static string HeavyAttack_TwoHanded_Name {
            get {
                return ResourceManager.GetString("HeavyAttack_TwoHanded_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Melee Attack Speed ähnelt.
        /// </summary>
        internal static string MeleeAttackSpeed {
            get {
                return ResourceManager.GetString("MeleeAttackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One-Handed Melee Damage ähnelt.
        /// </summary>
        internal static string OneHandMeleeDamage {
            get {
                return ResourceManager.GetString("OneHandMeleeDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path of the Fighter ähnelt.
        /// </summary>
        internal static string PathFighter {
            get {
                return ResourceManager.GetString("PathFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighter ähnelt.
        /// </summary>
        internal static string PathFighterRoot {
            get {
                return ResourceManager.GetString("PathFighterRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shieldbearer I ähnelt.
        /// </summary>
        internal static string Shield1 {
            get {
                return ResourceManager.GetString("Shield1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shieldbearer II ähnelt.
        /// </summary>
        internal static string Shield2 {
            get {
                return ResourceManager.GetString("Shield2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shieldbearer III ähnelt.
        /// </summary>
        internal static string Shield3 {
            get {
                return ResourceManager.GetString("Shield3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A powerful attack that gains a percentage of your shield&apos;s armor rating as additional base damage. Your shield also grants significantly more armour while this skill charges. ähnelt.
        /// </summary>
        internal static string ShieldCharge_Description {
            get {
                return ResourceManager.GetString("ShieldCharge_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield Charge ähnelt.
        /// </summary>
        internal static string ShieldCharge_Name {
            get {
                return ResourceManager.GetString("ShieldCharge_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield Defense ähnelt.
        /// </summary>
        internal static string ShieldDefense {
            get {
                return ResourceManager.GetString("ShieldDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single-Handed I ähnelt.
        /// </summary>
        internal static string SingleHanded1 {
            get {
                return ResourceManager.GetString("SingleHanded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single-Handed II ähnelt.
        /// </summary>
        internal static string SingleHanded2 {
            get {
                return ResourceManager.GetString("SingleHanded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single-Handed III ähnelt.
        /// </summary>
        internal static string SingleHanded3 {
            get {
                return ResourceManager.GetString("SingleHanded3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed I ähnelt.
        /// </summary>
        internal static string TwoHanded1 {
            get {
                return ResourceManager.GetString("TwoHanded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed II ähnelt.
        /// </summary>
        internal static string TwoHanded2 {
            get {
                return ResourceManager.GetString("TwoHanded2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed III ähnelt.
        /// </summary>
        internal static string TwoHanded3 {
            get {
                return ResourceManager.GetString("TwoHanded3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-Handed Melee Damage ähnelt.
        /// </summary>
        internal static string TwoHandMeleeDamage {
            get {
                return ResourceManager.GetString("TwoHandMeleeDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string VitalStrike_Description {
            get {
                return ResourceManager.GetString("VitalStrike_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vital Strike ähnelt.
        /// </summary>
        internal static string VitalStrike_Name {
            get {
                return ResourceManager.GetString("VitalStrike_Name", resourceCulture);
            }
        }
    }
}
